### ISSUE TITLE
Top level IfLetStore or SwitchStore doesn't update in Previews

### ISSUE THREAD

**Issue by rcarver** [pointfreeco/swift-composable-architecture#1542]
### Description

When the outer-most view is a `IfLetStore` or `SwitchStore`, the case doesn't update when run in previews.

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

The case should update when the state changes!

### Actual behavior

The state of the store/viewStore changes but the visible case of the If or Switch doesn't reflect that state.

### Steps to reproduce

1. Run the following SwiftUI Previews
2. The progress spinner should be visible when the count is 0
3. Note that the spinner is still visible though the count has changed to 100 due to the timer
4. Uncomment the outer `VStack` and note that the spinner disappears as expected

Note
* Using the button *might* update the view but it's flakey.
* Running the app in a simulator behaves correctly.

```swift
import ComposableArchitecture
import SwiftUI

public struct SimpleFeature: ReducerProtocol {
  public struct State: Equatable {
    var count: Int = 0
  }
  public enum Action: Equatable {
    case tappedButton
    case delayedIncrement
    case task
  }
  public func reduce(into state: inout State, action: Action) -> EffectTask<Action> {
    switch action {
    case .delayedIncrement:
      state.count += 100
      return .none
    case .tappedButton:
      state.count += 1
      return .none
    case .task:
      return .run { send in
        try await Task.sleep(nanoseconds: NSEC_PER_SEC)
        await send(.delayedIncrement)
      }
    }
  }
}

struct SimpleView: View {
  let store: StoreOf<SimpleFeature>
  var body: some View {
    //        VStack {
    IfLetStore(store.scope(state: { $0.count == 0 ? nil : $0 })) { store in
      WithViewStore(store) { viewStore in
        VStack {
          Text(viewStore.count.formatted())
          Button("Increment") { viewStore.send(.tappedButton) }
        }
      }
    } else: {
      WithViewStore(store) { viewStore in
        VStack {
          ProgressView()
          Text(viewStore.count.formatted())
          Button("Increment") { viewStore.send(.tappedButton) }
        }
      }
    }
    .task { await ViewStore(store).send(.task).finish() }
    //        }
  }
}

struct SimpleView_Previews: PreviewProvider {
  static var previews: some View {
    SimpleView(store: Store(
      initialState: SimpleFeature.State(),
      reducer: SimpleFeature()
    ))
  }
}
```

### The Composable Architecture version information

17ec3d9f8148dcbe2644447a7531542b27ac9b51

### Destination operating system

iOS 16

### Xcode version information

Version 14.1 beta 3 (14B5033e)

### Swift Compiler version information

```shell
swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.134.3 clang-1400.0.29.51)
Target: x86_64-apple-macosx12.0
```

**Comment by gohanlon** [comment]
I reproduced this using Xcode 14.1 RC (14B47) and TCA main at [2ea76a2](https://github.com/pointfreeco/swift-composable-architecture/commit/2ea76a2901ea35640d56630232181439430c12e1).

**Comment by tgrapperon** [comment]
Hey @rcarver! Indeed, this is caused by the magic SwiftUI does with previews where non-unary views are promoted to multiple previews. In this case `IfLetStore` returns a `_ConditionalContent` and SwiftUI Previews is maybe assuming that it should create multiple previews, but it doesn't. You can reproduce the same behavior in vanilla SwiftUI:
```swift
struct TestView: View {
  @State var isOn = false
  var body: some View {
    Group {
      if isOn {
        Color.red
      } else {
        Color.blue
      }
    }
    .task {
      try? await Task.sleep(for: .seconds(0.5))
      isOn.toggle()
    }
  }
}
```
When you launch them in the simulator, these views are wrapped in a `HostingView` that automatically infers a `VStack`, as you can check by previewing or running:
```swift
struct CheckView: View {
  var body: some View {
    TestView()
    TestView()
  }
}
```
In SwiftUI Previews, it will create two distinct previews, and it the simulator, it will stack them.
I'm not sure we can do a lot about it, as we clearly don't want to wrap `IfLetStore` content implicitly.

**Comment by rcarver** [comment]
ah! Excellent explanation @tgrapperon thanks. I'll close this issue.

1. Maybe add a checkbox to the Bug form "can you reproduce this in vanilla SwiftUI" so I don't forget :)
2. Definitely a previews gotcha, worth some docs or a best practice?

**Comment by tgrapperon** [comment]
I think it's worth filing a feedback with the vanilla repro, as this is likely not the expected behavior. For example, this simplified version doesn't work either:
``` swift
struct TestView: View {
  @State var isOn = false
  var body: some View {
    if isOn {
      Color.red
    } else {
      Color.blue
       .task {
         try? await Task.sleep(for: .seconds(0.5))
         isOn.toggle()
       }
    }
  }
}
```
This is definitely counter-intuitive.

The simplest workaround is to probably wrap your previews yourself in `previews: some View` when you spot something odd. You can probably implement a few extensions on `View` to help in the process, like a `.preview()` that would wrap in a `ZStack` or `NavigationStack` or whatever makes sense[^1].
A few days ago, I was considering suggesting a `Troubleshooting` section to the docs where one could have gathered known issues and workarounds, for example `Textfield` emitting twice, `Navigation` being reset, etc. This could probably be the better place to mention this quirkiness.

[^1]: I'm using this kind of trick to inject a very colorful background that helps when working on vibrant views in isolation. I also have helpers to present modally content that will mostly be presented modally, etc.
I even have something that automatically switches the states of `Store` from a list I provide to check that the animates correctly, and also a refined version of #1234 that allows me to print anything to a virtual console without having to spin an app. Possibilities are endless!
