### ISSUE TITLE
PassthroughSubject cant be used as Effect

### ISSUE THREAD

**Issue by pteasima** [pointfreeco/swift-composable-architecture#159]
**Describe the bug**
When using `Effect.concatenate()` with an `Effect` thats created from a `PassthroughSubject` using `.eraseToEffect()`, any `Effects` that appear in the `.concatenate()` after the `PassthroughSubject` aren't subscribed. 
**To Reproduce**
Ive minimized it to this failing test https://github.com/pteasima/swift-composable-architecture/blob/01a885ee9514836c8206ed3ad23fd3334988972f/Tests/ComposableArchitectureTests/EffectTests.swift#L162-L174
**Expected behavior**
Combine isn't a trainwreck.
**Actual behavior**
It is.

**Environment**
 - Xcode 11.5
 - Swift 5.2.2

This is just an FYI and feel free to close this as soon as you wish. I haven't debugged this more, it will likely boil down to a Combine bug. Maybe there's workarounds or at least we could override `eraseToEffect()` for `PassthroughSubject`s and make it `@available(*, unavailable)`. Im hesitant to burn time on it so close to WWDC.

**Comment by mbrandonw** [comment]
I believe this is because `.concatenate` waits until the first publisher completes before allowing the second to start. If you completed the subject with `subject.send(completion: .finished)` you would then see that the second effect starts.

If you want both to start immediately you could use `.merge` instead.

In general one has to be careful using `.concatenate` with long living effects. It can lead to later effects not being executed like you expect.

**Comment by pteasima** [comment]
Well, shit 😀 I thought the name `.concatenate` felt wrong but I couldnt remember `.merge`. And as luck would have it, I had a few usecases where I meant `.merge` but `.concatenate` worked just fine, plus it worked if I used `.none` instead, so I was sooooo sure its the `PassthroughSubject` 😀

Makes sense, Thanks 💯

**Comment by pteasima** [comment]
I guess since this came up. How do you guys feel about `Effect: ExpressibleByArrayLiteral`?

**Comment by mbrandonw** [comment]
We had that in the very beginning stages of the library but decided to remove because we were worried it would not be clear if `[e1, e2]` meant `.merge(e1, e2)` or `.concatenate(e1, e2)`.
