### ISSUE TITLE
Clarify a sentence in readme

### ISSUE THREAD

**Issue by anohren** [pointfreeco/swift-composable-architecture#173]
When reading the readme, this is understandable:

> State: A type that describes the data your feature needs to perform its logic and render its UI.
Action: A type that represents all of the actions that can happen in your feature, such as user actions, notifications, event sources and more.
Environment: A type that holds any dependencies the feature needs, such as API clients, analytics clients, etc.
Reducer: A function that describes how to evolve the current state of the app to the next state given an action. 

But it's not clear to me what the next sentence wants to say:

> The reducer is also responsible for returning any effects that should be run

The function returns _effects_? Did I miss something here?

**Comment by gkaimakas** [comment]
An `Effect` is a special type of `Publisher`. It is also responsible for feeding events to the reducer.

It might seem perplexing but once you get your hands dirty, it's pretty easy! The guys have extensive example that help too!

**Comment by anohren** [comment]
Thanks! Since the type is not introduced, can I assume it's defined by another module that I should already be familiar with?

**Comment by mluisbrown** [comment]
The `Effect` type is defined in the Effect.swift source file where it is also documented. It is just a type of `Publisher` which publishes zero or more `Action` values that can make the state machine transition to another state. 
It’s called Effect because it can carry out side effects, synchronously or asynchronously, that result in an Action.

**Comment by anohren** [comment]
Thanks, that's a clear description. 

Then my suggestion is that the readme should introduce the type before assuming the reader knows anything about it.

**Comment by mbrandonw** [comment]
@anohren Thanks for bringing this up! I just made a quick update to the readme to make it clear that by "effect" we mean `Effect`: https://github.com/pointfreeco/swift-composable-architecture/pull/174

I don't think too much more needs to be said in that bullet point because the rest of the section builds a reducer from scratch and better describes how to put together the ingredients, and at the end of the section mentions that the Examples directory contains a lot more demos.

**Comment by stephencelis** [comment]
Closing this as #174 has been merged. Thanks!
