### ISSUE TITLE
Dependency override issue with 0.49.1

### ISSUE THREAD

**Issue by jaanussiim** [pointfreeco/swift-composable-architecture#1811]
### Description

Dependency override that is working in 0.48.1 is failing when switching to 0.49.1

Root dependency is failable. When scoping child feature, usable dependency is extracted from the root dependency.

Calling the dependency in child reducer BestOffers is getting the root failure.

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Steps to reproduce

Sample project here: https://github.com/jaanussiim/tca-dependencies-issue

Scoping the usable dependency:
https://github.com/jaanussiim/tca-dependencies-issue/blob/main/TCADependencies/Application.swift#L29

Creating the child dependency:
https://github.com/jaanussiim/tca-dependencies-issue/blob/main/TCADependencies/OffersClient.swift#L22

### The Composable Architecture version information

0.49.1

### Destination operating system

iOS 16.2

### Xcode version information

14.2

**Comment by tgrapperon** [comment]
Hey @jaanussiim!
The problem is that you modelled your dependency as a reference type. Between the moment you reduce `BestOffers.Action.loadOffer` and the moment it calls `offersClient.loadOffers()`, the `OffersClient` has changed back to the root one. You can check this out by capturing the `offersClient` reference in your `.fireAndForget`:
```swift
case .loadOffers:
  return EffectTask.fireAndForget { [offersClient = self.offersClient] in
    try await offersClient.loadOffers()
  }
}
```
This will not crash. But this will however be very prone to weird issues like these that are complex to debug. I think that you'd get warnings with the `-warn-concurrency` flag.

I'm not sure either you'll end-up sending message to the correct instances, but it looks like your dependency is a singleton, so it looks stable-ish.

I would advise to remodel your dependency into something that exposes a value type that can be safely captured by the `.fireAndforget` (and `.run` and `.task`) closures. I think that wrapping it in a struct should perform the capture trick automatically for you, and would probably be enough to fix your issue.

I'm not sure what has exactly changed between 48.1 and 49.1 (well, a lot has changed! but don't know what caused the difference of behavior), and I'm not sure this is a regression.

**Comment by tgrapperon** [comment]
As I'm thinking about it, you were implicitly capturing the `self` reducer value in your `.fireAndForget`, and the value resolves using the current dependencies that are non-defaults because you did set the live value manually. I think that it would have worked if you weren't defining these live dependencies.
Given the way `@Dependency` are resolved, I think that they should still return what they saw when they were created, so it is maybe a regression after all.

**Comment by mbrandonw** [comment]
Yeah there does seem to be some kind of regression here, but it's difficult to track down exactly why it's happening. Thomas' PR is probably the way to go, and in fact it's how I started with the concept but later moved to `@Dependency` thinking we want the latest binding possible. But in retrospect I guess it is more explicit to say "escape the dependencies as they exist _right now_" rather than "how they will exist at the time of access".

Independent of the PR and fix, I will also echo Thomas' sentiments on the actual dependency. Using a reference type is not going to be great because it allows changes to it to be observed outside `dependency`/`withDependencies` scopes. And it's true that your client cannot be made `Sendable` (due to the `lazy var`), and hence this code won't even compile in Swift 6.

So, I would also suggest turning this dependency into a sendable type, which means thinking of another way to handle the `topOffers`.

**Comment by stephencelis** [comment]
@jaanussiim You can bump Dependencies to 0.1.2 to see the fix. We'll also make sure the next release of TCA requires this version.
