### ISSUE TITLE
Incorrect order of "reduce" calls in `forEach` modifier

### ISSUE THREAD

**Issue by dankinsoid** [pointfreeco/swift-composable-architecture#1836]
### Description

In my project, I use `forEach` and in situations when an action came to an id that is not in the IdentifiedArrayOf, I want an empty state to be created for the id. I tried this code:
```swift
Reduce { state, action in
  switch state {
  case let .element(id, _):
     state.createElementIfNeeded(for: id)
     return .none
  }
}.forEach(\.elements, action: /Action.element) {
  ElementReducer()
}
```
but it doesn't work because `ElementReducer()` reduces first although I would expect `Reduce` to be the first to reduce.

I suggest to change lines 116-122 in `ForEachReducer.swift`:
```swift
  @inlinable
  public func reduce(
    into state: inout Parent.State, action: Parent.Action
  ) -> EffectTask<Parent.Action> {
    self.reduceForEach(into: &state, action: action)
      .merge(with: self.parent.reduce(into: &state, action: action))
  }
  ```
to:
```swift
  @inlinable
  public func reduce(
    into state: inout Parent.State, action: Parent.Action
  ) -> EffectTask<Parent.Action> {
    self.parent.reduce(into: &state, action: action)
      .merge(with: self.reduceForEach(into: &state, action: action))
  }
  ```
Also it would be nice to add optional parameter to `forEach` call:
```swift
}.forEach(\.elements, action: /Action.element) {
  ElementReducer()
} createElementIfMissed: { id, state in
  Element()
}
```

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

Parent reducer is called first in `forEach` modifier

### Actual behavior

Parent reducer is called last in `forEach` modifier

### Steps to reproduce

1. Create any reducer with `forEach` modifier
2. Send any action

### The Composable Architecture version information

0.43.0

### Destination operating system

iOS 15

### Xcode version information

Xcode 14.1

### Swift Compiler version information

```shell
swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
Target: x86_64-apple-macosx12.0
```

**Comment by tgrapperon** [comment]
Hey @dankinsoid! This behavior is deliberate: In TCA, the `.element(Element.ID, Element.Action)` is assumed to be an action emitted by `Element`s when gathered in an `IdentifiedArray`. For this reason, emitting the `.element(id, _)` action without the corresponding element having a state wouldn't make sense, as only this element can emit this kind of action. This is not a technical issue, and we could imagine to silently recovering, but this is considered a developer error since the origin of this library, as we always want an action emitted by a domain to loop back into the domain. Nil'ing-out this domains state because of an action it emitted before it saw it coming back would exactly break this "rule".

So the `.forEach` modifier makes sure that these child reducers run first to avoid the kind of situation where the parent reducer nils out the child's state before the child receives the action it emitted.

I don't know if there is a dedicated section about this issue in the documentation, but this is the exact rationale that justifies why `ifLet` and `forEach` reducers are not provided in the form of top-level reducers `IfLet`, `ForEach`, as the modifier style allow to bake the current ordering. I'll check if I can find additional resources on the topic.

You can workaround your issue by installing a dedicated `Reduce` reducer that creates the element if required:
```swift
var body: some Reducer {
  Reduce {
    if case let .element(id, _) = $1 {
      $0.createElementIfNeeded(for: id)
    }
  }
  Reduce {
    // Core logic
  }
  .forEach(…)
}
```

**Comment by dankinsoid** [comment]
@tgrapperon okay thank you
