### ISSUE TITLE
Build app error after update from version 0.46.0

### ISSUE THREAD

**Issue by artemkrachulov** [pointfreeco/swift-composable-architecture#1884]
### Description

We have a fully working app built with TCA version 0.46.0. After the update, the compiler shows an error:

![Screenshot 2023-01-31 at 11 20 05 AM](https://user-images.githubusercontent.com/7997760/215719480-65c3c41b-05ef-437d-9b1e-0b31568927a3.png)

For project generation we use [Tuist](https://tuist.io/)

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### The Composable Architecture version information

0.48.0

### Destination operating system

iOS 16

### Xcode version information

Version 14.2 (14C18)

### Swift Compiler version information

```shell
swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)
Target: x86_64-apple-macosx13.0
```

**Comment by mbrandonw** [comment]
Hi @artemkrachulov, sorry about this but we had to make a [small breaking change](https://github.com/pointfreeco/swiftui-navigation/releases/tag/0.6.0) to how alert actions are handled. There are 2 ways you can fix this. You can either add this to your Package.swift in order to force the version of SwiftUINavigation that TCA uses to be before the change:

```swift
.package(url: "https://github.com/pointfreeco/swiftui-navigation", from: "0.5.0")
```

…or you can update to the newest TCA.

Let me know how that works for you.

**Comment by artemkrachulov** [comment]
@mbrandonw update to the newest TCA works, thx
