### ISSUE TITLE
catchToEffect deprecation without alternative for supported platform

### ISSUE THREAD

**Issue by jaredh159** [pointfreeco/swift-composable-architecture#1986]
### Description

huge fan of TCA and your work. thanks so much for all your libraries. 🙏 

currently working with the `prerelease/1.0` branch, building a macOS app that targets `10.15` - `13`.  `10.15` (Catalina) is [a supported platform](https://github.com/pointfreeco/swift-composable-architecture/blob/prerelease/1.0/Package.swift#L9) according to the `Package.swift`.

but, I'm getting deprecation warnings trying to use `.catchToEffect`, with a suggestion that I iterate over `publisher.values`.  that's all well and good, but `publisher.values` isn't available until macOS 12. so, i can't convert to it.

can this warning/deprecation be scoped to platforms that support the alternative? or is there some alternative I'm not aware of that would work without deprecation/warning as far back as `10.15`?

and I'm hoping you aren't planning on removing this api soon, right? unless I'm missing something that would force a platform compat bump all the way to macos 12.

apologies if there's something obvious i'm overlooking here.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

Expected no deprecation for an api without an alternative.

### Actual behavior

Got a deprecation of an api without an alternative.

### Steps to reproduce

use `catchToEffect` when targeting macos < 12

### The Composable Architecture version information

`prerelease/1.0` branch

### Destination operating system

macOS 10.15 - 13

**Comment by stephencelis** [comment]
Hi @jaredh159! Not sure if you've pulled recently, but last week we added to the deprecation message to also suggest using `Effect.publisher`, which acts as a Combine bridge for earlier for older platforms:

https://github.com/pointfreeco/swift-composable-architecture/blob/132cb3bae2d333c75ff2c952086d1dcd53ba392e/Sources/ComposableArchitecture/Effects/Publisher.swift#L383

You can then use `Publisher.catch` and other Combine operations on the publisher in that block:

```swift
return .publisher {
  self.dependencyThatCanFail()
    .map { .response(.success($0)) }
    .catch { .response(.failure($0)) }
}
```

I'm going to convert this to a discussion since I think it's more of a question than a bug.
