### ISSUE TITLE
Navigating more views does not working

### ISSUE THREAD

**Issue by john-ahmedov** [pointfreeco/swift-composable-architecture#2034]
### Description

While I am creating app with more navigations, For example: 1st screen navigates, 2nd screen, then 3rd, 4th, 5th screens.
When I am navigating 1st to 2nd works fine, but when navigating 2nd to 3rd, it dismiss 3rd screen automatically. It is really annoying.

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

It should navigate properly to other screens without dismissing it

### Actual behavior

3rd screen dismisses automatically

### Steps to reproduce

1. Navigate 1st, 2nd, 3rd screen.

### Destination operating system

iOS 16.0

### Xcode version information

Xcode 12.3

**Comment by mbrandonw** [comment]
Hi @john-ahmedov, this is most likely just a bug in vanilla SwiftUI. Many times it is exacerbated by observing too much state in TCA, but without seeing any code it is hard to say. You should audit any place you are using `observe: { $0 }` in a `ViewStore` or `WithViewStore` in order to whittle down state to the bare essentials (see [this article](https://pointfreeco.github.io/swift-composable-architecture/main/documentation/composablearchitecture/performance#View-stores)).

I am going to convert this issue into a discussion since it is most likely not a problem with the library. Please include more code or a sample project if you would like to discuss further.
