### ISSUE TITLE
Unexpected updates in ifLet for UIKit

### ISSUE THREAD

**Issue by fonkadelic** [pointfreeco/swift-composable-architecture#216]
I've slightly modified the TicTacToe UIKit example with the following code in `AppViewController`

```swift
self.store
  .scope(state: { $0.login }, action: AppAction.login)
  .ifLet(then: { [weak self] loginStore in
    self?.setViewControllers([LoginViewController(store: loginStore)], animated: false)
  },
  else: {
    print("else")
  })
```

After logging in you will notice that the else branch is triggered twice.

I've looked into this for a bit and the underlying problem seems to be  the combination of the two scope functions that are involved. Both of them trigger `handleEvents:receiveOutput` in the `ifLet` UIKit function. 

One other thing I've tried was verifying this behaviour in a unit test. But strangely I was not able to.

**Comment by fonkadelic** [comment]
I have now a unit test in place that shows the issue:
https://github.com/fonkadelic/swift-composable-architecture/blob/feature/ifLetUIKit/Tests/ComposableArchitectureTests/IfLetUIKitTests.swift

**Comment by mbrandonw** [comment]
Hey @fonkadelic, thanks for the report! We can definitely reproduce the issue you are seeing. We found a way to fix that test with the following (very rough code):

https://github.com/pointfreeco/swift-composable-architecture/compare/iflet#diff-49640fa34bee173aaeb48f28f5ad4561R46-R65

But then it breaks other things :/

The root of the problem is that we shouldn't be using `handleEvents` to inject that `else` behavior into the publisher. That causes troubles when deriving other stores, since each derived store holds onto the parent. So that's why we tried rewriting `ifLet` from scratch, not using `scope` or `handleEvents`. It seemed to work at first, but then we noticed it breaks child views that create view stores. We're not sure what's going on, but hopefully we can figure it out sometime soon.

Let us know if you discover anything!

**Comment by fonkadelic** [comment]
It's probably nothing related to the Combine framework. I've applied the changes to the TCA Reactive Swift fork and it has the exact same behavior.

**Comment by mbrandonw** [comment]
It is related to `.handleEvents`, and really it means we shouldn't be using `.on` in ReactiveSwift either. Hopefully we can find a solution that avoids both operators.

**Comment by fonkadelic** [comment]
Ah sorry I wasn’t clear enough. I’ve applied the changes from your branch with the rewrite that uses a view store.
