### ISSUE TITLE
v0.54.0 and below broken due to SPM package resolution

### ISSUE THREAD

**Issue by venkr** [pointfreeco/swift-composable-architecture#2244]
### Description

A recent update to [swiftui-navigation](https://github.com/pointfreeco/swiftui-navigation/pull/112) is not backwards compatible with v0.54.0 and below of this package.

As a result, when attempting to resolve the package graph, we run into:
`product '_SwiftUINavigationState' required by package 'swift-composable-architecture' target 'ComposableArchitecture' not found in package 'swiftui-navigation'.`

We've resolved this issue by updating to v0.55.0, but it might be worth considering package pinning via `exact` for SPM to better handle semver violations by underlying packages. 

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

Tag v0.54.0 should remain functional regardless of changes in dependencies

### Actual behavior

Tag v0.54.0 and below no longer work due to a backwards-incompatible API change

### The Composable Architecture version information

0.54.0

### Destination operating system

macOS 13.5

**Comment by mbrandonw** [comment]
Hi @venkr, yes this was unfortunately necessary due to a bug in Xcode's build system and how they handle libraries with underscores in the name. FWIW we did detail this problem in the SwiftUINavigation release:

https://github.com/pointfreeco/swiftui-navigation/releases/tag/0.8.0

> We've resolved this issue by updating to v0.55.0, but it might be worth considering package pinning via `exact` for SPM to better handle semver violations by underlying packages.

Using `exact` to pin versions will only cause more problems in the future. It makes it difficult for libraries to evolve naturally and will create lots of resolution errors. FWIW, it is possible for you to perform exact pinnings for all of TCA's transitive dependencies. Simply depend on the libraries explicitly and set their versions to exact. That will force TCA to use those versions of the libraries.

Since I don't think there is really anything else we can do to help with this issue in the library (other than letting people know they need to update their libraries), I am going to close the issue.
