### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by mycroftcanner** [pointfreeco/swift-composable-architecture#236]
The Composable Architecture uses GitHub issues for bugs. For more general discussion and help, please use [the Swift forum](https://forums.swift.org/c/related-projects/swift-composable-architecture) first.

I ran:

> git clone git@github.com:pointfreeco/swift-composable-architecture.git 

and opened the workspace.

Now whenever I try to compile any of the targets I get the following error:

"Authentication failed because no credential were provided"

<img width="273" alt="image" src="https://user-images.githubusercontent.com/55385694/88460888-7bc34600-ce97-11ea-8e90-f338efa17972.png">

When I tap on the error, an alert is displayed asking me to use my GitHub account... 

I tap on my GitHub account and it asks for personal token... so I create a personal token... 

I try to compile again and I still get an authentication error.

I guess you probably never encountered that error because you have the right credentials for this repo but it is really not straightforward for a user like me to get it working. I have no idea what to change to compile these targets.

**Comment by boudavid** [comment]
That's weird, I just cloned the repo, opened `ComposableArchitecture.xcworkspace` and launch the `CaseStudies (SwiftUI)` target without any issue. 🤔

**Comment by heiberg** [comment]
This error message seems to indicate that there is a problem cloning the package dependencies from GitHub (`combine-schedulers` and `swift-case-paths`).

I would double check that any GitHub account you might have added to Xcode is correctly configured. Alternatively, try removing that GitHub account, and just let Xcode download the dependencies anonymously.

Most likely this problem is not specific to the Composable Architecture repo for you, but is a more general GitHub connection issue.

**Comment by mycroftcanner** [comment]
Sorry, it was a problem with git config. In .gitconfig file it was set to

url.git@github.com.insteadOf "https://github.com/:
