### ISSUE TITLE
Mapping AnyPublisher to Effect with the Latest Swift Composable Architecture

### ISSUE THREAD

**Issue by StefaniOSApps** [pointfreeco/swift-composable-architecture#2505]
### Description

Hello, I am currently facing a challenge while trying to map a network request or WebSocket connection that is returned as an `AnyPublisher` to an `Effect` in a reducer using the swift-composable-architecture library.

In the previous versions, I noticed that we could use `catchToEffect` or `eraseToEffect` functions, as shown in the examples provided in the `pointfreeco/composable-core-location` repository. However, I’ve found that `composable-core-location` is not compatible with the latest version of swift-composable-architecture.

Here is a simplified version of my current implementation:

```swift
struct APIError: Error, Equatable {}

struct AppState: Equatable {
    var data: Data?
}

enum AppAction {
    case fetchData
    case dataResponse(Result<Data, APIError>)
}

struct AppEnvironment {
    var apiClient: APIClient
}

let appReducer = Reducer<AppState, AppAction, AppEnvironment> { state, action, environment in
    switch action {
    case .fetchData:
        return environment.apiClient.fetchData()
            .map(AppAction.dataResponse)
            .eraseToEffect()
    case .dataResponse(let result):
        switch result {
        case .success(let data):
            state.data = data
            return .none
        case .failure:
            return .none
        }
    }
}

class APIClient {
    func fetchData() -> AnyPublisher<Data, APIError> {
        // Implementation of network request that returns AnyPublisher<Data, APIError>
    }
}
```

As shown in the code above, I am trying to use an `APIClient` that fetches data and returns an `AnyPublisher`. The `fetchData` action is supposed to trigger this API client to fetch data and then map the result to a `dataResponse` action. But I’m unsure if this is the recommended way to handle this, especially with the updates to the swift-composable-architecture.

I would greatly appreciate your guidance or examples of best practices for handling this scenario with the latest version of the library. How should we map an `AnyPublisher` to an `Effect` professionally in this context?

Thank you in advance for your assistance.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

I anticipated that the `swift-composable-architecture` and `composable-core-location` libraries would be compatible, allowing seamless integration and mapping of `AnyPublisher` to `Effect` using functions like `catchToEffect` or `eraseToEffect`. The expectation is to have a streamlined, efficient, and type-safe way to handle asynchronous actions and effects emanating from network or WebSocket requests.

### Actual behavior

However, in practice, I have encountered compatibility issues between the two libraries. The `catchToEffect` and `eraseToEffect` functions, previously used for error handling and type erasure, are not functioning as expected with the latest version of `swift-composable-architecture`. This has led to difficulties in mapping `AnyPublisher` instances returned from network requests to `Effect` in reducers.

### Steps to reproduce

1. Update the `swift-composable-architecture` to the latest version.
2. Attempt to use it in conjunction with the `composable-core-location`.
3. Try to map an `AnyPublisher` resulting from a network or WebSocket request to an `Effect` using the `catchToEffect` or `eraseToEffect` functions.
4. Observe the incompatibility issues and the lack of type safety or efficient error handling mechanisms.

I believe that enhancing the compatibility between these two libraries and providing clear documentation on handling such scenarios in the context of the latest updates would be highly beneficial for developers leveraging these tools for reactive and functional programming in Swift.

### The Composable Architecture version information

1.2.0

### Destination operating system

iOS 17

### Xcode version information

Xcode 15

### Swift Compiler version information

```shell
Default
```

**Comment by kamcma** [comment]
`composable-core-location` has not been updated to post-Swift-concurrency TCA. I think because it depends on types that have been removed from > 1.0 TCA (`EffectPublisher`), if you require `composable-core-location`, you'll need to stay on `"0.43.0"..<"1.0.0"` TCA for the time being. [The maintainers do intend to update `composable-core-location` eventually](https://github.com/pointfreeco/composable-core-location/discussions/34#discussioncomment-4511028).

More generally, the > 1.0 TCA-Combine integration is now the [`Effect.publisher` static method](https://pointfreeco.github.io/swift-composable-architecture/1.2.0/documentation/composablearchitecture/effect/publisher(_:)), rather than the old `.eraseToEffect()` method, since `Effect` is no longer explicitly a Combine publisher. But that won't work for current `composable-core-location`, because it is not a vanilla Combine library, and explicitly depends on older TCA.

**Comment by ynechaev** [comment]
It would be super helpful if this aspect was covered in docs or case studies. Combine integration is a common case scenario.

**Comment by kamcma** [comment]
Vanilla Combine is totally compatible with TCA >1.0, via [the `Effect.publisher` method](https://pointfreeco.github.io/swift-composable-architecture/1.9.0/documentation/composablearchitecture/effect/publisher(_:)). The issue is `composable-core-location` is not a vanilla Combine library; it is specifically a TCA <1.0 `EffectPublisher` library.
