### ISSUE TITLE
fireAndForget Environment Side Effect

### ISSUE THREAD

**Issue by wendyliga** [pointfreeco/swift-composable-architecture#271]
I know TCA have `fireAndForget` for an `Effect` that outputing `Never`, but i have a case that needs to `fireAndForget` a network call

environment
```swift
    struct Environment {
        var save: (String) -> Effect<Response, Never>
    }

    let environment = Environment {
        URLSession.shared.dataTaskPublisher(for: url)
            .decode(type: Response.self, decoder: jsonDecoder)
            .eraseToEffect()
    }
```

expectation
```swift
 case let .save(value):
        /// fireAndForget a network request
        return env.save(value).fireAndForget()
```

but on my case, i can't map my side effect to never(?) on my `Environment`, maybe we can extend `fireAndForget` for general type ?

Thanks before

**Comment by wendyliga** [comment]
i guess, it can be done by
```swift
struct Environment {
        var save: (String) -> Effect<Never>
    }

    let environment = Environment {
        var cancellable = Set<AnyCancellable>()

        URLSession.shared.dataTaskPublisher(for: url)
            .decode(type: Response.self, decoder: jsonDecoder)
           .sink(receiveCompletion: {_ in }, receiveValue: {_ in })
           .store(in: &cancellable)
    }
```

so i can call it with 
```swift
case let .save(value):
        /// fireAndForget a network request
        return env.save(value).fireAndForget()
```

**Comment by boudavid** [comment]
Hey @wendyliga,

I'm just curious why do you need to use `.fireAndForget` in that case ? Isn't it better to have a `<Success, Failure>` in case the network request fails ?

I have a similar case where I need to delete something on the backend and I just care about whether the request succeeded or failed.

```swift
// Success and Failure are just empty structs.
func delete(id: String) -> Effect<Success, Failure> {
    var request = URLRequest(url: URL(string: "path/to/delete/something/\(id)")!)

    request.httpMethod = "DELETE"
    return URLSession.shared
        .dataTaskPublisher(for: request)
        .map { _, _ in Success() }
        .mapError { _ in Failure() }
        .eraseToEffect()
}
```

Is this helpful ?

By the way, I think these kind of questions are better suited for the [forums](https://forums.swift.org/c/related-projects/swift-composable-architecture/61). 😃

**Comment by wendyliga** [comment]
@boudavid oh my bad, will move to forums for the future.

yes, the requirement is exactly fire and forget. no matter what result it may get.
just send request to server and forget about it

**Comment by mbrandonw** [comment]
Hey everyone, thanks for the discussions, this API is definitely not perfect right now and we'd love to improve it.

In our opinion the strangeness is kind of combing from inconsistencies in the Combine APIs. For example, Combine as a `ignoreOutput` for converting `Publisher<Output, _>` to a `Publisher<_, Failure>`, but not corresponding method `ignoreFailure` to do the same for failures.

Also Combine as `.setFailureType(to:)` for converting `Publisher<_, Never>` into `Publisher<_, Failure>` for any type `Failure`, but no corresponding `.setOutputType(to:)` that works for publishers of `Never` outputs.

These tools could be used to accomplish everything you want without us needing to come up with new APIs for it. Your first example could be:

```swift
env.save(value)
  .ignoreOutput()
  .ignoreFailure()
  .setOutputType(to: AppAction.self)
  .eraseToEffect()
```

It's a lil verbose, but at least it's super descriptive that you are wanting to ignore everything about what this effect can produce. Maybe the APIs could even be a little more succinct so that you could do ignore+set in the same step:

```swift
env.save(value)
  .ignoreOutput(setOutputType: AppAction.self)
  .ignoreFailure()
  .eraseToEffect()
```

That would be pretty nice. So really we should probably file some feedbacks with Apple to have them fix the weird asymmetries in their APIs, and in the meantime @stephencelis and I will think a bit more about how to handle this situation no the TCA side.

Until then you can use something like the following to "fire and forget" effects that output non-`Never` values:

```swift
env.save(value)
  .ignoreOutput()
  .eraseToEffect()
  .fireAndForget()
```

**Comment by stephencelis** [comment]
Submitted FB8563288: Combine is missing some symmetric operations for Output/Failure.

**Comment by wendyliga** [comment]
@mbrandonw @stephencelis @boudavid one thing leads to another 😀
really appricate the time for your response, thank you

**Comment by stephencelis** [comment]
Given the CombineExt helpers added, I think we can close this out and folks that are interested can depend on the project! Thanks @jasdev!
