### ISSUE TITLE
State not updating when sending event from UITextField

### ISSUE THREAD

**Issue by sger** [pointfreeco/swift-composable-architecture#273]
**Describe the bug**
I have a simple UITableView with a custom UITableViewCell which contains a UITextField when the text changes i'm sending an event from the view store  in order to get the new text and apply some transformations.The UI freezes and the UITextField loses focus.

**To Reproduce**
[CounterListApp.zip](https://github.com/pointfreeco/swift-composable-architecture/files/5147228/CounterListApp.zip)

**Expected behavior**
State must receive the new text without freezing the UI.

**Environment**
 - Xcode 11.6
 - Swift 5.2
 - OS (if applicable): iOS 13

**Comment by stephencelis** [comment]
@sger I think the issue you are seeing is due to the fact that `reloadData()` is called on the table view for every key stroke. The data source should probably only be driven by insertions/removals/moves. You can get halfway there with the following change:

```diff
 self.viewStore?.publisher.counters
+  .removeDuplicates(by: { $0.count == $1.count })
   .sink(receiveValue: { [weak self] in self?.dataSource = $0 })
```

This won't account for moves, but if you add some kind of identifier to each row you could detect that, as well.

**Comment by stephencelis** [comment]
@sger Did the above solution work for you and is this issue OK to close out?

**Comment by sger** [comment]
@stephencelis Thanks this was the solution.
