### ISSUE TITLE
Pulling back an item from an array of arrays

### ISSUE THREAD

**Issue by pcolton** [pointfreeco/swift-composable-architecture#29]
I have an array of items. Those items also have an array of other child items. I sometimes need to present a single child item to the user, filtered from the top level array, but I'm not properly wrapping my head around the correct approach in pulling back the changes.

Should I be somehow nesting forEach reducers (both sets of arrays contain Identifiable items)?

**Comment by stephencelis** [comment]
Hi @pcolton! That sounds about right to us. You should be able to take `childItemReducer` and `forEach` it into the domain of `itemReducer`, which you can `forEach` into the main reducer. Could you share some code so we can all help steer you towards something that compiles?

**Comment by pcolton** [comment]
@stephencelis, thanks for the follow up. So I created a full sample project (attached) that shows my issue. I know I'm close, but I'm missing one critical part in terms of how changes to the nested child bubble their way all the way back up to the top AppState.

I think my use of computed properties in the AppState is not quite right for this situation. Thanks for any insight you can provide.

[nested-arrays.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4594845/nested-arrays.zip)

**Comment by stephencelis** [comment]
@pcolton Looking quickly at your example, I see that the computed properties you `pullback` and `forEach` along do not have their setters defined. A setter needs to be implemented for mutations to make their way from the local reducer to the global reducer's state.

You can also imagine what it would look like if you defined `appReducer` manually: what would it mean to mutate `downloadedEpisodes` and `allEpisodes` state directly?

**Comment by pcolton** [comment]
I guess the 'missing part' for me is that even though the returned items, for example the [EpisodeState] array from 'allEpisodes', are Identifiable, in the 'setter' I would have to manually walk my own 'shows' array and put them back into their right place. 

I guess I was wondering if that could be automated somehow in the reducer? But in asking that question, I think I might see the answer, that it can't "jump" from reducing into allEpisodes and also update a completely different item, in this case, 'shows'. Correct?

**Comment by stephencelis** [comment]
The "automation" would be that glue code you write in the computed property. As long as it's possible for you to write those two setters then the `pullback` and `forEach` should "just work."

**Comment by pcolton** [comment]
Got it working, thanks. I guess I was mentally opposed to all that logic in the setter, but I understand now. And yes, it did "just work". However, as an aside, I found an update issue along the way. I'm assuming it's a SwiftUI bug, but let me show you in case it's something in TCA...

Basically, the self.episodeList won't update the view unless I wrap it in a WithViewStore, even though it already does that later...

```swift
    var episodeList: some View {
        VStack(alignment: .leading) {
            Text("All: ").font(.title)
         
            HStack {
                ForEachStore(self.store.scope(
                    state: \.allEpisodes,
                    action: AppAction.episode(id:action:)), id: \.id) { episodeStore in
                        
                        WithViewStore(episodeStore) { viewStore in
                            EpisodeView(viewStore: viewStore)
                        }
                    }
            }
            .frame(maxWidth: .infinity, alignment: .leading)
        }
    }
    
    var body: some View {

        VStack {
            
            WithViewStore(self.store) { viewStore in
                self.episodeList
            }

            EpisodeRow(store: self.store.scope(
                state: \.downloadedEpisodes,
                action: AppAction.episodeRow)
            )
        }
    }

```

**Comment by stephencelis** [comment]
@pcolton I'm not sure I can reproduce that behavior. I've pushed the following change: https://github.com/pointfreeco/swift-composable-architecture/compare/issue-29

Which eliminates the `WithViewStore` in the `body` of the Todos app's main view and moves the `ForEachStore` into another property and everything still appears to update. Would be interested in a repro if you can share, though!

**Comment by stephencelis** [comment]
(And if you believe what you're seeing _is_ a SwiftUI bug, please file feedback with Apple if you can!)

**Comment by pcolton** [comment]
Here is the project which shows the update bug. Lines 244 and 246 are commented out to produce the bug.

Just run, check one of the boxes on the top row and you'll see it doesn't update. If I add in the WithViewStore, it does.

[nested-arrays-updateissue.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4595614/nested-arrays-updateissue.zip)

**Comment by stephencelis** [comment]
@pcolton Ah, I see the problem. It's a little subtle but it has everything to do with how SwiftUI observes state changes.

In a typical app an `@ObservedObject` (or `@State`) would denote what state in a view is mutable and should be observed. The Composable Architecture provides `WithViewStore` as a convenience view that wraps an `@ObservedObject` under the hood.

In your code, `EpisodeView` is taking a `ViewStore` instead of a `Store`, and `EpisodeView` is not observing its state. There are 2 fixes for this:

  1. Wrap the `viewStore` on `EpisodeView` with `@ObservedObject`
    ```diff
    -var viewStore: ViewStore<EpisodeState, EpisodeAction>
    +@ObservedObject var viewStore: ViewStore<EpisodeState, EpisodeAction>
    ```

  2. Pass a _store_ along instead and use `WithViewStore` in the `body` of `EpisodeView`.

The reason you found that `WithViewStore(self.store) { ... }` fixes things is because it observes _all_ of store state, and whenever any of it changes it will reevaluate all of the views inside `{ ... }`.

Make sense? While we have some documentation written for this, we probably should write a more general guide around how to use stores and view stores to minimize view computations.

**Comment by pcolton** [comment]
I see, thanks. It is indeed subtle, but I understand. As always, I appreciate the help! 👍🏼

**Comment by JackYoung2** [comment]
Hi @stephencelis. Me and my team are struggling to understand the best way to use forEach reducer and identified arrays.

Our problem relates to this issue so I thought here would be a good place to ask it. 

If for example we updated allEpisodes with the new identified array, would the below code be problematic because we are generating an identified array on the fly with new ids every time state updated, and if so what would be the best pattern for computing identified array from existing state?

```
   var allEpisodes: IdentifiedArrayOf<EpisodeState> {
        get {
            let allEpisodes = shows.flatMap { $0.episodes }
            return IdentifiedArrayOf(
                uniqueElements: allEpisodes.map { EpisodeState(downloaded: $0.filename != nil, episode: $0
                ) }
                )
        }
        set {
            let allEpisodes = newValue.map { $0.episode }

            shows = shows.map { currentShow in

                var show = currentShow

                show.episodes = allEpisodes.filter { episode in
                    return show.episodes.contains { $0.id == episode.id }
                }

                return show
            }
        }
    }
```

Thanks for your help, if the question is not clear I can edit the demo project a bit further to make my point a bit clearer.
