### ISSUE TITLE
Observe method leak

### ISSUE THREAD

**Issue by juliensagot** [pointfreeco/swift-composable-architecture#2932]
### Description

Hi folks 👋 
It appears that the `observe` method is leaking, even when `self` is properly weakified inside the trailing closure, unless I'm doing some silly things.

<img src="https://github.com/pointfreeco/swift-composable-architecture/assets/1755698/f61ea6f3-d55c-4a9b-a92f-b24f429993b9" width=300>

-------

I've attached a sample macOS project where you can easily repro the issue:
[TCAPerceptionLeakSampleProject.zip](https://github.com/pointfreeco/swift-composable-architecture/files/14664801/TCAPerceptionLeakSampleProject.zip)

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Steps to reproduce

- launch the sample project
- attach **Instruments** using the **Leaks** template
- press the `Increment` button

### The Composable Architecture version information

1.9.2

### Destination operating system

14.4 (23E214)

### Xcode version information

Version 15.3 (15E204a)

### Swift Compiler version information

```shell
swift-driver version: 1.90.11.1 Apple Swift version 5.10 (swiftlang-5.10.0.13 clang-1500.3.9.4)
Target: arm64-apple-macosx14.0
```

**Comment by mbrandonw** [comment]
Hi @juliensagot, this most likely will be fixed when [this PR](https://github.com/pointfreeco/swift-perception/pull/52) of swift-perception is merged.

Could you help us verify this by adding an explicit dependency on swift-perception to your project and pinning it to the `explicit-animation` branch?

**Comment by mbrandonw** [comment]
Hi @juliensagot, how exactly can I reproduce the problem? I've run the app, increment the counter, and I don't see any leaks:

<img width="777" alt="tmp" src="https://github.com/pointfreeco/swift-composable-architecture/assets/135203/056ba4c8-ea8a-43dc-8d13-762410cf89a2">

Also, are you sure you are running the leaks instrument in `DEBUG`? Because the object that is showing up in your screenshot, `LockIsolated`, is only used in `DEBUG` mode:

https://github.com/pointfreeco/swift-perception/blob/db087559dcc50eedebdc7df6a0fb0c1e188e4229/Sources/Perception/PerceptionRegistrar.swift#L18-L21

**Comment by juliensagot** [comment]
Oh no, you are right, I was somehow profiling the app in debug mode…  
There are indeed no leaks! I'll close the issue, sorry 😅
