### ISSUE TITLE
Typing in a textfield recalls the whole body of View

### ISSUE THREAD

**Issue by chitvan832** [pointfreeco/swift-composable-architecture#30]
In the` Binding case study `if I type anything in `textfield` the whole View is recreated which make sense as we send a `BindingBasicsAction.textChange` causing state to change, but without using composable architecture, if I use `@State` for binding a value to textfield, it doesn't recreates the whole view.
According to my understanding, SwiftUI is smart enough to only re-render a particular subview when a value binded to it changes, in our case textfield.
Can we achieve this using composable architecture as this is more efficient while using complex views.

**Comment by stephencelis** [comment]
Hi @chitvan832!

> In the`Binding case study`if I type anything in `textfield` the whole View is recreated which make sense as we send a `BindingBasicsAction.textChange` causing state to change, but without using composable architecture, if I use `@State` for binding a value to textfield, it doesn't recreates the whole view.
> According to my understanding, SwiftUI is smart enough to only re-render a particular subview when a value binded to it changes, in our case textfield.

There's definitely a lot of undocumented magic around how SwiftUI decides to evaluate the `body` of a particular view. For the most part we should not have to worry about this, but it can definitely become a concern.

In the case of a `TextField` and `@State` binding, SwiftUI seems to avoid calling `body` if state is only used for the text field, but as soon as you access `self.text` for the purpose of rendering UI, `body` will be called with each keystroke:

```swift
struct MyView: View {
  @State var text = ""

  var body: some View {
    print("body evaluated")
    return VStack {
      Text(self.text)
      TextField("Untitled", text: self.$text)
    }
  }
}
```

> Can we achieve this using composable architecture as this is more efficient while using complex views.

[`WithViewStore`](https://github.com/pointfreeco/swift-composable-architecture/blob/be42d850ef3a8e9120dc82e874672718cb473607/Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift) is precisely what allows you to scope and describe what should be updated and how often. By default it deduplicates based on equatable state, but you can also describe the deduplication strategy with `removeDuplicates`. Most of the demos in the repo are quite simple and haven't done anything to optimize calls to `body`, but if you check out the Todos app, it does scoping to prevent unnecessary calls to `body`.

It is unlikely that the given example will cause too much churn, but you can approximate state's behavior by telling `WithViewStore` to consider all changes to be duplicates. For example:

```swift
WithViewStore(self.store.scope(state: \.text), removeDuplicates: { _, _ in true }) { viewStore in
  TextField(
    "Placeholder",
    text: viewStore.binding(send: Action.textFieldChanged)
  )
}
```

`WithViewStore` also comes with a tool that helps you debug how often it is called by tacking on its `.debug()` view modifier, which will log to the console whenever its content closure is evaluated.

```swift
WithViewStore(self.store) { viewStore in
  ...
}
.debug()
```

**Comment by mbrandonw** [comment]
Hi @chitvan832, do you have any other questions? Cool to close this issue?

**Comment by mbrandonw** [comment]
Gonna close this for now, but please feel free to re-open if you have more questions!

**Comment by natecraft1** [comment]
@stephencelis using this pattern with Textfields in a Store that is quite deeply nested, I am experiencing this effect where the text appearing is lagging significantly behind when I type it. Seems that there is some performance hit perhaps because all the parent reducers are called on every keystroke. Is there a way to prevent all the parent reducers from being triggered or some other way around this performance issue?

**Comment by siejkowski** [comment]
I've experienced a huge performance hit when using nested store too.

Have you tried profiling via Instruments to confirm what's taking the time? 

In my case, I've found that the Store.scope method was very slow, mostly because it is accessing the state from Combine's CurrentValueSubject multiple times going through the scoping hierarchy. And apparently CurrentValueSubject is really not performant.

This might be also what you're experiencing. I'll share my particular case just to show some context.

I had a store that was created through a 5 levels of scoping. It was for downloading the image asynchronously to present it in the SwiftUI lazy grid.

I've spend quite a time in the Instruments cycling through the "optimise and verify if the optimisation is working" loop. Unfortunately, no matter what I've tried, the viewStore.send method was always taking crazy long (like 70% of the total time) and all that time was taken because it was going through the scoping.

The workaround I landed on (and I'm happy with performance wise) was to change my stores architecture so that the asynchronous image store could be top-level. No need for scopes — no performance problems. It led me to way less elegant architecture though 🤷

**Comment by natecraft1** [comment]
Thanks for sharing @siejkowski, and interesting insight into the profiling findings. I ultimately had to just add an @State var as the textfield binding and only `send` when the user explicitly presses "Done". Not Ideal but gets the job done
