### ISSUE TITLE
@ObservedObject doesn't get notified from computed properties on iOS14

### ISSUE THREAD

**Issue by barksten** [pointfreeco/swift-composable-architecture#304]
I have a custom HostingController to update the status bar to reflect dark mode that are dependent on the apps content. In my AppState I have a computed property for the colorScheme.
When the ```someState``` gets updated in my reducer the viewStore signals the change. This works in iOS13 but not in iOS14. 

```swift
extension AppState {
    var activeColorScheme: ColorScheme {
        get { (someState == .foo || someState == . bar) ? .dark : .light }
    }
}

class MyHostingController<Content>: UIHostingController<Content> where Content : View {
    @ObservedObject var viewStore: ViewStore<AppState, AppAction>
    init(viewStore: ViewStore<AppState, AppAction>, rootView: Content) {
        self.viewStore = viewStore
        super.init(rootView: rootView)
    }
    @objc required dynamic init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    override var preferredStatusBarStyle: UIStatusBarStyle {
        switch self.viewStore.activeColorScheme {
        case .light:
            return .darkContent
        case .dark:
            return .lightContent
        @unknown default:
            return .lightContent
        }
    }
}

```
From my scene delegate:
```
let window = UIWindow(windowScene: windowScene)
            window.rootViewController = MyHostingController(
                viewStore: ViewStore(store),
                rootView: ContentView(store: self.store)
            
            self.window = window
            window.makeKeyAndVisible()
```

**Comment by mbrandonw** [comment]
Hi @barksten, thanks for the issue. It would help if you could provide a full code sample that we can compile to see the problem. 

There are few things that caught my attention in your code. First, your view store doesn't need `@ObservedObject` because that property wrapper is only intended to work with SwiftUI views. Right now it isn't doing anything special by being in a `UIViewController`.

Second, just because `someState` changes in your `AppState` it does not mean it will automatically propagate those changes to the status bar. You are in charge of doing that explicitly, which you could do by subscribing to the `viewStore.publisher` and calling `setNeedsStatusBarAppearanceUpdate` on the view controller whenever it changes.

Third, the `preferredStatusBarStyle` property is called by UIKit only in certain situations, such as app start up, and I believe when pushing/popping/presenting controllers, as well as when you explicitly call `setNeedsStatusBarAppearanceUpdate`. So, if this code was working in iOS 13 but not 14 I believe it would be because something was causing `preferredStatusBarStyle` to be called more often previously than it is now.

All in all I believe that this issue doesn't have to do with TCA directly, but rather how UIKit is being used, and possibly some internal changes that happened to UIKit between iOS 13 and 14.

**Comment by barksten** [comment]
Your right about the @ObservedObject thing. It was a copy&paste leftover..
I have a working repo demonstrating the issue here:
https://github.com/barksten/statusbar-example

Anyway, I don't blame TCA for this since there are a lot more things that diff between iOS13 and iOS14.

**Comment by stephencelis** [comment]
@barksten Definitely appears to be a change in iOS behavior and not a TCA bug. I think you'd see the same behavior in vanilla SwiftUI if you kept this state in a view model. You need to subscribe to state changes and call `setNeedsStatusBarAppearanceUpdate` to ensure that iOS knows to check the `preferredStatusBarStyle` property. In your code you can achieve this by adding a `sink` to your initializer:

```swift
class MyHostingController<Content>: UIHostingController<Content> where Content: View {
  var viewStore: ViewStore<AppState, AppAction>
  // 1️⃣ Add a cancellables set to your hosting controller to maintain view store subscriptions
  var cancellables: Set<AnyCancellable> = []
  
  init(viewStore: ViewStore<AppState, AppAction>, rootView: Content) {
    self.viewStore = viewStore
    super.init(rootView: rootView)

    // 2️⃣ Sink on activeColorScheme changes to call setNeedsStatusBarAppearanceUpdate
    self.viewStore.publisher.activeColorScheme
      .receive(on: DispatchQueue.main)
      .sink { [weak self] _ in self?.setNeedsStatusBarAppearanceUpdate() }
      .store(in: &self.cancellables)
  }
  // ...
}
```

**Comment by barksten** [comment]
Yes, I was a little trigger happy with opening this issue.
Anyway, thanks for the tips!
