### ISSUE TITLE
Catch-22 with optional reducers and onDisappear 

### ISSUE THREAD

**Issue by buscarini** [pointfreeco/swift-composable-architecture#333]
I have a view with a subview which uses a IfLetStore, so if some substate is not nil the view is presented. That subview sends an action in the "onDisappear". The issue is that if I set the substate to nil to make the subview disappear, the subview sends that action after the substate is nil, so the optional reducer crashes. 

1. Why the assertion in the optional function? 
2. How do I break this cycle? I guess I can just have a boolean to say if the view should be shown, but it feels weird having to do that.

**Comment by andreyz** [comment]
Personally I use the solution described at https://forums.swift.org/t/ifletstore-and-effect-cancellation-on-view-disappear/38272/23. Check out the whole thread it's quite comprehensive.

**Comment by stephencelis** [comment]
Hi @buscarini, I'm going to close this issue out since it's more of a question of how to model optional features, and there are workarounds these days, such as setting `breakpointOnNil: false` on the `optional` reducer. We have a lot we've been exploring when it comes to navigation that will hopefully shed some light on more best practices soon.

If you'd like to discuss other workarounds, please feel free to reopen this as a GitHub discussion 😄
