### ISSUE TITLE
Strange static shared state in live services

### ISSUE THREAD

**Issue by voidless** [pointfreeco/swift-composable-architecture#340]
Hi!
For example LiveAudioPlayerClient.swift contains static shared state which looks like an anti-pattern:
```swift
private var dependencies: [AnyHashable: AudioPlayerClientDelegate] = [:]
```
Maybe you should consider moving it to closure-captured memory of AudioPlayerClient methods (and all other services like that in this repository)
This will deallocate service state automatically when all instances of the service are deallocated.
Current implementation can push developers who use this example to adopt bad practice of static shared state for other usages, which can result in undetectable memory leaks.

```swift
extension AudioPlayerClient {
  static func makeLive() {
    var dependencies: [AnyHashable: AudioPlayerClientDelegate] = [:]
    return AudioPlayerClient(
      play: { id, url in
        .future { callback in
          do {
            let delegate = try AudioPlayerClientDelegate(
              url: url,
              didFinishPlaying: { flag in
                callback(.success(.didFinishPlaying(successfully: flag)))
                dependencies[id] = nil
              },
              decodeErrorDidOccur: { _ in
                callback(.failure(.decodeErrorDidOccur))
                dependencies[id] = nil
              }
            )

            delegate.player.play()
            dependencies[id] = delegate
          } catch {
            callback(.failure(.couldntCreateAudioPlayer))
          }
        }
      },
      stop: { id in
        .fireAndForget {
          dependencies[id]?.player.stop()
          dependencies[id] = nil
        }
      }
    )
  }
}
```

**Comment by mbrandonw** [comment]
Hi @voidless, we're certainly open to updating the examples to push the dependencies into the closure, however your proposal and the current code technically work the same.

The value returned from your `makeLive()` function will live for the entire duration of the application, as you can see [here](https://github.com/pointfreeco/swift-composable-architecture/blob/e1bd51b1761c9f7ab4001928c73f357c9116f807/Examples/VoiceMemos/VoiceMemos/SceneDelegate.swift#L20). It is never deallocated, and so the locally scoped `dependencies` dictionary will not be deallocated, and that is expected. Environments should be created a single time and then propagated to all features via the `pullback` operation.

The current code does not have a memory leak because the way one deallocates the memory for `AudioPlayerClientDelegate` is to return the `.stop(id:)` effect from a reducer. That will deallocate and remove it from the dependencies dictionary.

We understand that having this global data hanging around can seem worrisome, but in practice it can be made reasonable. In fact, SwiftUI must be managing a ton of global data in the background in order to track which view struct values belong to which view being drawn on the screen, amongst other things its tracking.

We are definitely open to ways of reducing any indirection there is with the global data, but we do not think your current suggestion makes any headway in that direction.
