### ISSUE TITLE
TestStore incorrectly scopes `.receive` steps

### ISSUE THREAD

**Issue by lukeredpath** [pointfreeco/swift-composable-architecture#357]
**Describe the bug**
When using a scoped `TestStore`, `.send` steps are correctly scoped to `LocalAction` but `.receive` steps are scoped to `Action`.

This seems like an easy thing to fix but I wasn't entirely sure if this was a bug or the expected behaviour.

**To Reproduce**

```swift
        struct ExampleState: Equatable {
            var nested: NestedState = .init()
        }
        struct NestedState: Equatable {}

        enum ExampleAction: Equatable {
            case nested(NestedAction)
        }
        enum NestedAction: Equatable {
            case example
        }

        let store = TestStore(
            initialState: ExampleState(),
            reducer: Reducer<ExampleState, ExampleAction, Void>.empty,
            environment: ()
        )
        .scope(state: \.nested, action: ExampleAction.nested)

        store.assert(
            .send(.example),
            .receive(.example) // <<< Type 'ExampleAction' has no member 'example'
        )
```

Changing the `.receive` to `.receive(.nested(.example))` works.

**Expected behavior**
Send and Receive should both be scoped to the locally scoped action.

**Environment**
 - Xcode 12.3
 - Swift 5.3.2

**Comment by stephencelis** [comment]
@lukeredpath This is by design, though it may be a little surprising and could definitely be better documented. Scoped test stores are generally intended to test view state and view actions (and I think view actions are only ever _sent_ by the user, never received by an effect). These user actions could also lead to side effects, though, where more general actions are received by the reducer, and in order to assert against these actions, the test store needs to be able to call `receive` with those actions and _not_ the same action type it sends.

Does that make sense? Any concerns with this approach?

**Comment by lukeredpath** [comment]
@stephencelis thanks for the explanation. I did have a suspicion it might be deliberate, but I wasn't sure why. Your explanation makes complete sense, I do think it would be helpful if this was a bit better documented - perhaps even renaming it to something like `viewScope` might make it more obvious?

**Comment by lukeredpath** [comment]
I think this can be closed, thanks for the updated docs.
