### ISSUE TITLE
External data store and composable architecture?

### ISSUE THREAD

**Issue by pcolton** [pointfreeco/swift-composable-architecture#38]
I have a question regarding external data stores (e.g. a database) that could potentially contain a large amount of data and how to reconcile that with TCA.

Assuming that ALL data cannot be loaded into the app state (into memory), what best practices can be recommended for managing this?

For example, querying the database for subsets of data for things like paging. How does this reconcile with reducers and pullbacks, or at least, how do you recommend it reconcile?

Thanks.

**Comment by stephencelis** [comment]
@pcolton I'll let others weigh in with more ideas, but I think one common approach is optionalize portions of your app's state and `nil` them out when they're not needed. This could be done by sending actions at `onAppear` and `onDisappear` that load and unload the view's data, or during navigation.

**Comment by pcolton** [comment]
Thanks. I'd love to hear how people are managing loading of data as well as persisting mutations of their data (for example, do you save to your database right at mutation time or some other time later, like a global save of state).

**Comment by Odrakir** [comment]
In my case I treat the Database as any other dependencies and database operations happen in Effects, the result of that operation then emits an action that updates the state. Alternatively I've considered other two other approaches:
- Do state updates optimistically and then fire the effect to update the database. In the improbable case that there's an error I should be able to roll back the state change.
- Fire the effect and then with a [subscription](https://github.com/pointfreeco/swift-composable-architecture/blob/master/Examples/CaseStudies/SwiftUICaseStudies/04-HigherOrderReducers-ElmLikeS.ubscriptions.swift) to the Database update the state somewhere else when the DB operation succeeds.

I'm using the first approach because it's the simpler to implement. I'm still not really sure which one is the best.

When it comes to loading there's an action that triggers it, and then state would update one way or the other depending on what of the above methods you are using.

Pagination could be done by adding the current page and limit to the state and have a reducer handle the database request appropriately. But I haven't done anything like that yet.
