### ISSUE TITLE
Performance issue when triggering child actions

### ISSUE THREAD

**Issue by jtouzy** [pointfreeco/swift-composable-architecture#381]
**Describe the bug**
We are currently facing a performance issue, when triggering an action from a large number of child components (in a ForEachStore), for loading their content. When the action is dispatched (from `onAppear` event), even if nothing is done inside it, the scroll is very laggy. I can't even find a good reason in Time Profiler, but I suspect all the actions are dispatched in Main thread, that causes the lag.

**To Reproduce**
I created a very lightweight project to reproduce the laggy scroll.
Just checkout this : https://github.com/jtouzy/PerformanceTestTCA
You will see the laggy scroll when you accelerate a bit (using a real device is better to see the difference).
If you just comment the line 42 in Child.swift, you will see that the scroll is perfectly fine, when no actions are triggered.
Even if you comment the reducer side effects for the action, and just return .none, the lag is still present.
That's why we are thinking about the thread.

Maybe you have a solution for this or maybe we need to implement it another way?

**Environment**
 - Xcode 11.4
 - Swift 5.3.2
 - iOS 14

**Comment by siejkowski** [comment]
I'd also love to hear and discuss the ideas on how to work around this in an elegant way.

In the meanwhile I can share the solution I currently use in my own project.
I had the exact same problem implementing async image loading in huge lazy grids in my own apps (collections with thousands of images). The send function, called in onAppear, was taking too much time, resulting in a sluggish scrolling performance.

My solution was to not use neither `forEach` reducer nor `ForEachStore`. I've extracted the async image loading stuff out of the main store entirely. I keep it the stores a separate struct, completely not connected to the rest of the TCA-driven app.

Here's this solution adopted to your test project:
```
public final class ChildStores {
  
  private var childStores: [String: Store<Child.State, Child.Action>] = [:]
  
  func createIfNeeded(for child: Child.State) -> Store<Child.State, Child.Action> {
    guard let store = self.childStores[child.id] else {
      let store = Store<Child.State, Child.Action>(
        initialState: Child.State(item: child.item),
        reducer: Child.reducer,
        environment: Child.Environment(loadItem: { item in
          // ... pass load item here, probably it's worth extracting it to separate objet to avoid duplication
        })
      )
      self.childStores[child.id] = store
      return store
    }
    return store
  }
}

let childStores = ChildStores() // doesn't need to be global, really, but it must be kept somewhere
```

Then you can use it when constructing the Child.View:
```

extension Main {
  struct View: SwiftUI.View {
    let store: Store<State, Action>

    var body: some SwiftUI.View {
      WithViewStore(store) { viewStore in
        ScrollView {
          LazyVGrid(columns: [.init(), .init()]) {
            ForEach(viewStore.children) { (item: Child.State) in
              Child.View(store: childStores.createIfNeeded(for: item))
            }
          }
        }
      }
    }
  }
}
```

As you can test, the performance is fine again. 

However, the solution, while working and pragmatic, looks more like a workaround to me. I'd love to scrap it for something better, so please share if you find anything!

**Comment by siejkowski** [comment]
Oh, and of course this brings the whole world of maintaining the separate stores (like clearing them when they are no longer needed etc.) which I'm dealing with in my actual project, I've just not include it in the samples above.

**Comment by manmal** [comment]
Just an idea, could you have an ImageLoader in the Environment which offers Publishers for loading the images? I think images are of ephemeral nature anyway, and don’t need their state persisted in a store. The ImageLoader can also employ caching if necessary.

**Comment by siejkowski** [comment]
Yeah, but how the View uses the image (or any kind of data) then? The view doesn't have the access to the environment, it only has the access to the state via view store. So even if ImageLoader does the caching and stuff, the image still has to be kept in the state so that it's exposed through the view store to the view.

Ofc you can just inject the ImageLoaded to the view directly. It is also cool, but it means you're just not using the TCA for that part of the app.

**Comment by manmal** [comment]
@siejkowski 

> you can just inject the ImageLoaded to the view directly
True, I think that's what I'd end up doing.

> but it means you're just not using the TCA for that part of the app
IMO that's ok - TCA is probably not meant to be a low-level, high-frequency information bus.

**Comment by siejkowski** [comment]
> IMO that's ok - TCA is probably not meant to be a low-level, high-frequency information bus.

With the current performance constraints looks like TCA is not a good tool for such use cases, I agree. 

I wonder if it could be improved by some internal optimisation. Time Profiler has led me to believe that what really slows action sending is Combine and the usage of CurrentValueSubject for keeping state in store. Maybe using an alternative mechanism there (custom subject?) could help?

**Comment by manmal** [comment]
Yeah, since the store isn't thread safe anyway, that would probably work. CombineExt has a ReplaySubject would could probably adapted to storing only one value quickly: https://github.com/CombineCommunity/CombineExt/blob/main/Sources/Subjects/ReplaySubject.swift

**Comment by Pwyll28** [comment]
For me, the me main issue is that scope operations + equality tests are on the main thread.
An alternative would be to expose state via a Publisher and then scope is done by creating a new store with the parent exposed state.
(Sorry for the "RxSwift" boilerplate I'm doing some tests in a side project and I'm more confortable with RxSwift rather than Combine)
```swift
  public func scope<LocalValue, LocalAction>(
    state toLocalState: @escaping (State) -> LocalValue,
    distinctUntilChanged: @escaping (LocalValue, LocalValue) -> Bool,
    action fromLocalAction: @escaping (LocalAction) -> Action
  ) -> Store<LocalValue, LocalAction> {
    let childState = state
      .map(toLocalState)
      .distinctUntilChanged(distinctUntilChanged)
    let localStore: Store<LocalValue, LocalAction> = .init(
      state: childState,
      initialValue: toLocalState(internalValue.value),
      environment: environment
    )
    let parentDiposable = localStore
      .action
      .map(fromLocalAction)
      .subscribe(action)
    localStore.parentDiposable = parentDiposable
    return localStore
  }
```
With the corresponding private initializer
```swift
  // Initializers
  private init<Environment>(
    state: Observable<State>,
    initialValue: State,
    environment: Environment
  ) {
    self.environment = environment
    self.state = state
    self.internalValue = .init(value: initialValue)
  }
```

**Comment by jtouzy** [comment]
It would be interesting to get the point of view of @stephencelis or @mbrandonw about this.

**Comment by mbrandonw** [comment]
Thanks for all the discussion! We investigated this a bit this morning and there's definitely more work to be done with `ForEachStore`, in particular sending lots of actions in a `ForEachStore`. We don't have any solutions right now, but a couple of comments:

* First, running the project on a device in release mode shows much better performance than the simulator. It's still not perfect, but it's also not nearly as horrendous.
* Second, the work we are doing in `ForEachStore` seems a bit convoluted and probably not necessary. For example, replacing `ForEachStore` in the project with something as simple as this has much better performance:

    ```swift
    WithViewStore(store.scope(state: \.children.indices)) { viewStore in
      ForEach(viewStore.state) { index in
        Child.View(
          store: self.store.scope(
            state: { state in state.children[index] },
            action: { action in Main.Action.child(index: index, action: action)})
        )
      }
    }
    ```

   However, this is a little dangerous to do with the project as-is because it won't properly render re-orders (items will change but `indices` will not). It would be necessary to upgrade `children` to be an `IdentifiedArray` of `Child.State`. In reality, anytime you are using `ForEachStore` you should probably be using `IdentifiedArray` anyway because it's a far safer way of dealing with a `ForEach` data source.

* Finally, it can be instructive to compare TCA solutions with what the corresponding solution would look like in vanilla SwiftUI. We built a little vanilla version of your project using an `ObservableObject` view model and saw that performance was pretty good, but still when scrolling through lots of rows it would stutter. This must be because of all the `DispatchQueue.main.async`'s firing.
   
    However, even this vanilla demo isn't a fair comparison to TCA. In TCA we are able to split off the child domain so that it is fully isolated from the parent. To do that in vanilla SwiftUI we would need some kind of mechanism for splitting of "child view models" from the parent view model, and there really hasn't been any movement in the community on how to attack that problem. One should try to accomplish that in vanilla SwiftUI in order to have a fully fair comparison.

We'll keep y'all updated with whatever we find in the future, and please let us know if you stumble upon anything!

Also, I am going to convert this issue to a [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions) as that's a bit more appropriate for this.
