### ISSUE TITLE
2FA SwiftUI crashes in TicTacToe example

### ISSUE THREAD

**Issue by rhys-rantmedia** [pointfreeco/swift-composable-architecture#395]
**Describe the bug**
In the TicTacToe example application, when you choose the SwiftUI application flow and opt into the Two Factor Auth. section, when you tap "Next" after typing in `1234`, the app with crash with the error:

```
Fatal error: "LoginAction.twoFactorDismissed" was received by an optional reducer when its state was "nil". This can happen for a few reasons:
```

with a long list of reasons as to why it's potentially crashed.

This crash appears to be caused by `LoginSwiftView.swift` line num. 71. where the app sends `.twoFactorDismissed` to the now nil'd out `LoginState`, as the `NavigationLink` receives `false` for the `isActive` binding.

**To Reproduce**
 - Open the TicTacToe sample application
 - Select SwiftUI version
 - Enter `2fa@test.com` in the Email field
 - Enter `password` in the Password field
 - Tap Log in
 - Enter `1234` and tap Submit
 - App navigates to the New Game screen, then immediately crashes

**Expected behavior**
I expected the app to progress to the New Game screen and not crash 😅

**Screenshots**
<img width="1294" alt="Screenshot 2021-02-24 at 09 25 43" src="https://user-images.githubusercontent.com/52451686/108983622-f7cc7900-7686-11eb-9417-2ab7a2e7ae63.png">

**Environment**
 - Xcode 12.4
 - Swift 5.3
 - Composable Architecture version 0.15.0

**Additional context**
If you login with the 2FA flow through the UIKit version, it doesn't crash, and retains the login if you navigate backwards and switch to the SwiftUI version.

**Comment by mbrandonw** [comment]
Hi @rhys-rantmedia, we dug deep this morning and uncovered that it's due to a SwiftUI bug 😭.

It's actually related to this issue: https://github.com/pointfreeco/swift-composable-architecture/issues/363. It seems that enabling/disabling `NavigationLink` is a little buggy, and in this case it causes an unexpected action to be sent into the store, thus causing the assertion failure you see. Disabling this one single line fixes it:

https://github.com/pointfreeco/swift-composable-architecture/blob/86d6e3551437a88ecd73a789753fd2151761b17d/Examples/TicTacToe/Sources/Views-SwiftUI/LoginSwiftView.swift#L80

I'll be submitting a PR to fix this soon.

It's also worth noting that this isn't a _crash_ but rather an `assertionFailure`, so it only happens in `DEBUG`, not `RELEASE`. We do this because it can help catch programmer errors and silent failures. However, we do have a PR (https://github.com/pointfreeco/swift-composable-architecture/pull/296) where we plan to turn the `assertionFailure` into a breakpoint so that you can continue execution after.

**Comment by mbrandonw** [comment]
Actually the above is incorrect... I accidentally had some code commented out that led me to believe things were working when they were not 🙁

But, we did find the real culprit. It appears to be the `Form` used in `LoginView`. If you comment out this form everything works as expected:

https://github.com/pointfreeco/swift-composable-architecture/blob/86d6e3551437a88ecd73a789753fd2151761b17d/Examples/TicTacToe/Sources/Views-SwiftUI/LoginSwiftView.swift#L37

We've seen other weird issues with `Form`s, such as `.onDisappear` getting called early, so perhaps it's all related. I filed this feedback awhile ago, and if I can ever reproduce this problem in a vanilla SwiftUI app I'll file another one: https://gist.github.com/mbrandonw/2b1eefef3d939074fa040a7a0c7ab377

**Comment by rhys-rantmedia** [comment]
Ahhh, that's such odd behaviour from SwiftUI!

I did see some of the other ones related to sending `.dismiss` actions from a `.onDisappear` closure, and wondered if it was similar...

Great to hear about #296! Is there any sort of timescale for when that PR might be merged?

Thanks for responding so quickly!

**Comment by mbrandonw** [comment]
It's going to take us a little more time to prepare the PR because we need to get rid of `Form` which means we have to style the view ourselves. We may not be able to do that for a few days or a week, but if you wanted to take a stab at removing `Form` and applying some basic styling to look reasonable then we would happily accept a PR!

**Comment by ericlewis** [comment]
@mbrandonw I also have ran into a similar issue in a similar fashion, but wasn't related to a form. It seems when unwinding some views that they call viewDidAppear as they are torn down.

**Comment by mbrandonw** [comment]
@ericlewis do you have any code you could show that reproduces the problem?

**Comment by ericlewis** [comment]
@mbrandonw I will TRY to create a repro project with minimal change, but it's in our production app currently. I do have a solution for it, but less than optimal.

**Comment by ericlewis** [comment]
@mbrandonw this is the most minimal example I can make that reproduces the issue.

[ReproLogoutIssue.zip](https://github.com/pointfreeco/swift-composable-architecture/files/6038442/ReproLogoutIssue.zip)

**Comment by ericlewis** [comment]
I have a work around for the above code too, it is quite odd.

**Comment by rhys-rantmedia** [comment]
> It's going to take us a little more time to prepare the PR because we need to get rid of `Form` which means we have to style the view ourselves. We may not be able to do that for a few days or a week, but if you wanted to take a stab at removing `Form` and applying some basic styling to look reasonable then we would happily accept a PR!

Oops, sorry, I meant the #296 PR, for the breakpoint version of `optional()`

**Comment by mbrandonw** [comment]
Ahhh, yes, we plan on discussing that very soon.

**Comment by ferologics** [comment]
@ericlewis care sharing the workaround? I'm being blocked by this very issue

**Comment by lukeredpath** [comment]
@ericlewis did you find a fix for this problem? I'm hitting a near identical issue - in our login, if MFA is needed we push an MFA code entry screen, then on successful login we replace our entire logged out state with the logged in state, just as in your example - this seems to cause the `.onAppear` on the root login screen to fire, where we dispatch an action to a view store whose state no longer exists.

**Comment by ericlewis** [comment]
> @ericlewis did you find a fix for this problem? I'm hitting a near identical issue - in our login, if MFA is needed we push an MFA code entry screen, then on successful login we replace our entire logged out state with the logged in state, just as in your example - this seems to cause the `.onAppear` on the root login screen to fire, where we dispatch an action to a view store whose state no longer exists.

My fix for this was basically creating a "forgivablePullback" that logs a warning in debug and like normal pullback - does nothing in prod. It doesn't seem to cause issues in production (no crash) and no crash in debug (but still a helpful warning)

I believe this is due to issues with SwiftUI itself and lifecycle management of certain types of views. For reducers that I definitely want to crash I just use a normal pullback.

**Comment by ericlewis** [comment]
> @ericlewis care sharing the workaround? I'm being blocked by this very issue.
> 
> 
> 
> EDIT: looks like the [0.16.0 release](https://github.com/pointfreeco/swift-composable-architecture/releases/tag/0.16.0) contains a "fix" where the `assertionFailure` is replaced by a **breakpoint** in `DEBUG` builds.

This does work but even then you may not want the breakpoint. So a swift (hehe) custom implementation of pullback seems to work for me!

**Comment by lukeredpath** [comment]
Right, that makes sense. I've done something similar already, we have a `.whenLoggedIn` reducer which is a specialised form of pullback but explicitly checks the state before doing anything, such that the normal pullback logic isn't hit. Certainly something I can fallback on if I can't find a workaround. I'm using an explicit `@ObservedObject var viewStore` in this view which might be related, I'm going to see if `WithViewStore` changes anything. The weird thing this code was working until recently so I'm wondering what has changed!

**Comment by lukeredpath** [comment]
So `WithViewStore` didn't make a difference. I'm pretty sure `.onAppear` is firing because the `body` of that view is being re-evaluated - I'm not even sure how it's possible for this to happen. If that view's store's state is `nil`, then it should have been removed from the hierarchy entirely by the parent `IfLetStore` by that point, so how is it possible for the view to be evaluated - I can even inspect the `viewStore.state` and see a value even though it should be `nil`.

**Comment by fabstu** [comment]
FWIW `ForEachStore` also had an issue with re-evaluating the body with an ID that was removed from the collection already, dunno whether that's relevant. The body was re-evaluated before the parent body. Worked around it with IfLet there, not rendering the row and after the ID gets finally removed the row vanishes entirely. https://github.com/pointfreeco/swift-composable-architecture/issues/434

**Comment by lukeredpath** [comment]
The problem in this case is that the view being re-evaluated is already wrapped in an `IfLetStore`.
