### ISSUE TITLE
WithViewStore not refreshing 

### ISSUE THREAD

**Issue by alexito4** [pointfreeco/swift-composable-architecture#58]
**Describe the bug**

While making a SwiftUI view everything was going okey until suddenly the view stopped updating after changes on the store happened. 

I've added `debug()` both in the reducer and in the `WithViewStore` and the logs show the output I'm expecting. Although I would expect to receive a log for the reducer and then for the view update, currently there is always a final view update log missing.

It seems like SwiftUI is not observing correctly the changes. Maybe is related to `GeometryReader`, if I remove that view from the hierarchy then a single update happens haver loading data, but nothing else after that.

Note that keeping a `self.viewStore` as `ObservedObject` manually instead of using `WithViewStore` seems to resolve the problem.

**To Reproduce**
[WithViewStoreNotRefreshing.zip](https://github.com/pointfreeco/swift-composable-architecture/files/4604345/WithViewStoreNotRefreshing.zip)

```swift
    var body: some View {
        WithViewStore(self.store) { viewStore in
            GeometryReader { proxy in //// <- REMOVING THIS LAYER HELPS A BIT (refreshes once so the else content is displayed, but no more refreshes after that)
                ZStack(alignment: .bottom) {
///// THIS JUST EVALUATES THE IF INITIALLY BUT NEVER AGAIN, SO ELSE IS NOT DISPLAYED
                    if viewStore.somestate == nil {
                        ...
                    } else {
                       ...
                    }
                }
            }
        }
    }
```

**Expected behavior**
Views should refresh after the effect has finished.

**Environment**
 - Xcode 11.4
 - Apple Swift version 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29)
 - iOS 13.4

**Additional context**
I've reducer the problem from the App I'm building into the example attached. The original view is way more complex so I would have assumed something else was interfering but the reduced example is not that big so hopefully it helps. I will keep digging.

**Comment by mbrandonw** [comment]
Hey @alexito4 thanks for the report!

You are correct there is some weird behavior here, and it's something we've run into ourselves. We actually have this called out in the documentation:

https://github.com/pointfreeco/swift-composable-architecture/blob/d2240d0e76c1a758dbadbf737ceefc888b2e807c/Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift#L7-L18

This bug is even reproducible in vanilla SwiftUI code, so it's not related to TCA at all. We've filed feedbacks and have gotten a response that it is definitely a bug in SwiftUI.

You have two options for working around this. First, sometimes it's possible to put the `GeometryReader` on the outside of the `WithViewStore`, and then everything works correctly. We are able to do this in the animations case study:

https://github.com/pointfreeco/swift-composable-architecture/blob/d95caece62e6e2904d6b72fcef5306fa99fbf1bf/Examples/CaseStudies/SwiftUICaseStudies/01-GettingStarted-Animations.swift#L36-L37

It's not always possible to do that, but if it is then it's the easiest workaround.

If you can't flip the views then gotta use the `ViewStore` as a `@ObservableObject`, which requires a small amount of manual work. We demonstrate this in the voice memos app:

https://github.com/pointfreeco/swift-composable-architecture/blob/d2240d0e76c1a758dbadbf737ceefc888b2e807c/Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift#L346-L352

Can you give that a shot and let us know if it works out? 

Hopefully this is fixed in SwiftUI soon!

**Comment by alexito4** [comment]
> We actually have this called out in the documentation

Dang! I'm so sorry! I totally read that days ago and I knew there was some issue with the geometry reader, in my mind that's why I nested it inside because otherwise the sizes were wrong. Now I realise that causes this other issue, sorry for not reading it again ^^'

I juggled some geometry readers around but ended up moving the viewStore to a property, seems safer and easier to maintain. 

Thank you @mbrandonw 🤗

**Comment by ferologics** [comment]
This is still an issue, if anyone's wondering.

**Comment by doesnotexist** [comment]
> This bug is even reproducible in vanilla SwiftUI code,

@mbrandonw  can you share a code snippet that reproduces the bug?

**Comment by mbrandonw** [comment]
> @mbrandonw can you share a code snippet that reproduces the bug?

We've got links to feedbacks we have submitted to Apple in the documentation of `WithViewStore`:

https://github.com/pointfreeco/swift-composable-architecture/blob/edfe198d01044da01a636f09046fb2293c51c991/Sources/ComposableArchitecture/SwiftUI/WithViewStore.swift#L11-L20

Here's a gist of the feedback, which shows how to reproduce the bug in vanilla SwiftUI:

https://gist.github.com/mbrandonw/cc5da3d487bcf7c4f21c27019a440d18

**Comment by gapl** [comment]
@mbrandonw 

While this SwiftUI issue had a workaround in the previous versions of TCA, the proposed workaround is not applicable anymore (using latest version of TCA 1.9.2).

The previous workaround of adding an explicit `@ObservableObject` does not work anymore with migration to `@ObservableState`. Looking at [`VoiceMemoView`](https://github.com/pointfreeco/swift-composable-architecture/blob/2722a3466b78860ebf493103fc82ac85b076e1bd/Examples/VoiceMemos/VoiceMemos/VoiceMemo.swift#L104) which was used as an earlier example ([here](https://github.com/pointfreeco/swift-composable-architecture/blob/d2240d0e76c1a758dbadbf737ceefc888b2e807c/Examples/VoiceMemos/VoiceMemos/VoiceMemos.swift#L346-L352)), it also does not include an alternative workaround for this issue anymore.

Is there a known workaround that works with latest versions of TCA?
