### ISSUE TITLE
Better way to pullback IdentifiedArray from child state?

### ISSUE THREAD

**Issue by pcolton** [pointfreeco/swift-composable-architecture#61]
My simple AppState below shows how I have an IdentifiedArray which I pass on to a child view. When I do the pullback for homeView property, I walk the array items and set them back into my array. Is there a reducer forEach trick I can use to not need to manually remap my child array items back into my parent array?

```swift
struct AppState: Equatable {
    var allEpisodes: IdentifiedArrayOf<EpisodeState>
    
    var homeView: HomeViewState {
        get {
            HomeViewState(episodes: allEpisodes)
        }
        set {
            for episode in newValue.episodes {
                allEpisodes[id: episode.id] = episode
            }
        }
    }
}
```

For ref, my appReducer:

```swift
homeViewReducer.pullback(
        state: \AppState.homeView,
        action: /AppAction.homeView,
        environment: { _ in HomeViewEnvironment() }
    )
```

**Comment by mbrandonw** [comment]
Would it be more correct for your setter to be this:

```swift
set {
  allEpisodes = newValue.episodes
}
```

i.e. whatever the `homeViewReducer` does to the `episodes` array should be reflected in the `allEpisodes` field of `AppState`.

Otherwise, if the `homeViewReducer` removes some values from `episodes` it will never be reflected in the `AppState`.

There is something nuanced here that we haven't spent a ton of time talking about. In general, the `get` and `set` of a computed property should satisfy some rules:

* If you set a value and then get the value it should be the same as what was set:

  ```swift
  foo.bar = baz
  assert(foo.bar == baz)
  ```

* If you set a value and then set it again it's the same as if you just set it once:

  ```swift
  foo.bar = baz1
  foo.bar = baz2

  // should be the same as just doing
  foo.bar = baz2
  ```

* If you get the value and then set with that value it's the same as doing nothing:
  ```swift
  foo.bar = foo.bar

  // same as doing nothing
  ```

Your setter currently does not satisfy the first rule. In particular, if you had an app state with some episodes, and then set `homeView` with an empty array of episodes, the app state would not properly reflect that:

```swift
var appState = AppState(allEpisodes: [Episode()])

appState.homeView = HomeViewState(episodes: [])

appState.homeView != HomeViewState(episodes: [])
```

The setter probably doesn't satisfy the second property either.

So, all of this to say, the setter should probably be changed. Any reason it is the way it is right now?

**Comment by pcolton** [comment]
Thanks. The example above is more pseudocode than app. The issue is if I send a filtered list down to the child (a subset of the parent list), then I only want to update the same set coming back. What is best practices in that situation? 

(I hear you about deletions, I guess that would need to be handled a different way.)

**Comment by mbrandonw** [comment]
In the case of wanting to pass down a subset of items to a child reducer, and have any mutations made by the child be properly reflected in the parent, then yes what you sketched out above is essentially how'd you approach it. You need to replay the mutations from the child onto the parent. In order to handle deletions correctly you would need to take into account the `oldValue` and `newValue` in the setter.

**Comment by pcolton** [comment]
Perfect, thanks.
