### ISSUE TITLE
Crash in scope when running on device from Xcode

### ISSUE THREAD

**Issue by spekke** [pointfreeco/swift-composable-architecture#620]
**Describe the bug**
When running on device using debug configuration our app crashes in Store.scope. We think this relates to the size or complexity of our app state struct. 

**To Reproduce**
Unfortunately it's only reproducible in our app, we tried to make an example app that mimics how we have set up the app in our main project, but are unable to get the example app to crash. 

If we change to release configuration when running on device, it does not crash. 

**Screenshots**
![Screenshot 2021-06-28 at 10 26 59](https://user-images.githubusercontent.com/604657/123605006-b2b68000-d7fb-11eb-8fd8-ba55f929dee0.png)

![Screenshot 2021-06-28 at 10 56 15](https://user-images.githubusercontent.com/604657/123608910-7edd5980-d7ff-11eb-985b-c7af349a99c9.png)

**Environment**
 - Xcode 12.5
 - Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
 - iOS 14.6

**Comment by mluisbrown** [comment]
> We think this relates to the size or complexity of our app state struct.

You are almost certainly getting a stack overflow. This will manifest itself as `EXC_BAD_ACCESS`, and not always in the same place. See [this discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions/488) about the issue. You will probably need to use classes for some parts of your app state with a Copy on Write wrapper. There are examples in the discussion of the solution we have used in our project.

**Comment by westerlund** [comment]
> > We think this relates to the size or complexity of our app state struct.
> 
> You are almost certainly getting a stack overflow. This will manifest itself as `EXC_BAD_ACCESS`, and not always in the same place. See [this discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions/488) about the issue. You will probably need to use classes for some parts of your app state with a Copy on Write wrapper. There are examples in the discussion of the solution we have used in our project.

Thank you for your response, @mluisbrown! We added a few copy-on-write-wrappers to some parts of our complex `State` and everything works fine now! 
I don't know how this could be solved from within Composable Architecture, but it would be nice to have a section in the Readme raising this issue, since it'll probably be more widespread when SCA adoption increases!

**Comment by stephencelis** [comment]
I'm going to close this out since we're not sure what the next "actionable" step is. I'm not sure putting a note in the README would be the right place to surface, and hopefully searching "EXC_BAD_ACCESS" will lead folks to discussions like these. Some ideas:

- If the EXC_BAD_ACCESS is always in the same place, maybe we could add a comment there (although this could be easy to miss).
- If we decide to introduce a COW wrapper type with the library, maybe we could document the issue there.

If you'd like to start a discussion about next actionable steps, please do! There might be other ideas out there, as well (checking `MemoryLayout.size` in `DEBUG` builds, etc.).

**Comment by DaanyalMeyer** [comment]
Testing our app in iOS 16 and we started seeing these crashes all the time now.

**Comment by stephencelis** [comment]
@DaanyalMeyer have you tried refactoring your state with more boxes to reduce the stack size?

**Comment by DaanyalMeyer** [comment]
@stephencelis yes and it still crashes. I don't think it is an issue with the stack:

`Stack state: using 27808 bytes out of 1032192, 2.69% full.`

The crash happens after navigating down a bit and tapping on an action.

Everything works perfectly in iOS 15... in iOS 16 it crashes here:

![image](https://user-images.githubusercontent.com/24533076/174623830-febc6df0-fc14-4fb0-af55-c31c17698b79.png)

If I turn on address sanitisation it crashes right away.

**Comment by DaanyalMeyer** [comment]
@stephencelis boxing doesn't seem to help:

Stack state: using 27808 bytes out of 1032192, 2.69% full.

The app never crashed in iOS 15 and didn't require boxing.

On an iOS 16 device, it crashes after I navigate down the hierarchy and tap on an action.

If I turn on Address Sanitisation it crashes right away:

![image](https://user-images.githubusercontent.com/24533076/174626260-dfd77f02-b8ad-4771-9962-05c8c8c3fb5f.png)

**Comment by stephencelis** [comment]
@DaanyalMeyer Are you able to share a repro? How deep is the main thread in that screen shot above? If you're using the `recurse` reducer could you be infinitely recursing and overflowing the stack in that manner?

**Comment by tgrapperon** [comment]
> Also the TCA case study app crashes right away if you enable the address sanitiser on iOS16 with Xcode 14.

This is something I can't reproduce on my side. Running the iOS16b1 on an iPad Pro 10.5", with or without address sanitizer.

**Comment by DaanyalMeyer** [comment]
@tgrapperon I'm sorry the case study app crashed because I didn't clean after enabling address sanitation. 

I've found a much shorter path to the same crash... I am trying to create a repro.

**Comment by DaanyalMeyer** [comment]
If this can help... the crash is always happening here. 

I can confirm there is no infinite recursion and no stack overflow.

![image](https://user-images.githubusercontent.com/24533076/174660008-cc118900-aaf8-4799-aabb-6beb7c716e52.png)

Here the itemReducer was only called four times.

**Comment by stephencelis** [comment]
@DaanyalMeyer Have you pushed the repro somewhere we can try with steps on how to reproduce?

**Comment by DaanyalMeyer** [comment]
@stephencelis can we just give you access to a private repo? 

Another weird thing is that both the debug and release version crashes... If I build the app for profiling it doesn't crash at all.

**Comment by tgrapperon** [comment]
@DaanyalMeyer It seems that you're using the `StackState` I proposed in another discussion. Please note that no one has reviewed it yet, so I can't guarantee at 100% that it measures things accurately if ever my mental model of a stack is wrong. I've maybe slightly refined it in the PR #1152, but it should work the same. I've checked it in a recursive function and it rise as expected until the stack overflows, so I think it works, but I would be more serene if @stephencelis could have a look at it before making everyone lose their time!

**Comment by DaanyalMeyer** [comment]
@stephencelis we are using a box property wrapper everywhere we can in our states and environments. We also tried setting all cases as indirect if they have an argument. We created a limited app reducer that has nothing except navigating to the crash. 

All this effort kinda help a bit but if you navigate deeper in the recursive graph then we will have a stack overflow.

**Comment by adrianorezena** [comment]
So @DaanyalMeyer, we are having the same problem. Can you share the solution?

**Comment by stephencelis** [comment]
@DaanyalMeyer Sorry, we've been pretty busy, but would love to help troubleshoot if we can, if you're still having issues. Same goes to you, @adrianorezena. Want to shoot us an email and send us an invite to the repo with more info?

**Comment by kalupas226** [comment]
@stephencelis 

Hi, I have the same problem.
May I send you an email so that I can invite you to the repository?
I'll send the email address to the one associated with your GitHub account.

**Comment by DaanyalMeyer** [comment]
@stephencelis using CoW in both our state and environment helped a little but didn't solve the issue entirely. 

We are using a recursive reducer and the app lets you navigate through a massive graph and using CoW seems to just delay the inevitable crash.

The way we solved the stack overflow issue by creating a separate store whenever we navigate down the graph. We still use a recursive reducer to preload items before creating a substore and also to handle subitems in the current view controller.

```swift
public struct NavigationRoute: View {
  var store: Store<ItemState, ItemAction>
  
  @ObservedObject var viewStore: ViewStore<ViewState, ItemAction>

  struct ViewState: Equatable {
    let id: PropID
    let isPresenting: Bool
    let substore: Store<ItemState, ItemAction>?
    
    init(state: ItemState) {
      id = state.id
      isPresenting = state.substore != nil
      substore = state.substore
    }
  }
  
  public init(store: Store<ItemState, ItemAction>) {
    self.store = store
    self.viewStore = ViewStore(store.scope(state: ViewState.init(state:)), removeDuplicates: ==)
  }
  
  @ViewBuilder
  func destination(_ substore: Store<ItemState, ItemAction>?) -> some View {
    if let substore = substore {
      ZStack {
        NavigationRoute(store: substore)
        VCollection(store: substore)
      }
    }
  }
  
  public var body: some View {
    NavigationLink(
      destination: destination(viewStore.substore),
      isActive: viewStore.binding(
        get: \.isPresenting,
        send: { .setIsPresenting($0) }
      ),
      label: { EmptyView().id(viewStore.id) }
    )
  }
}
```


```swift
  @discardableResult
  fileprivate mutating func configureSubstore(
    state: ItemState,
    reducer: Reducer<ItemState, ItemAction, ItemEnvironment>,
    environment: ItemEnvironment
  ) -> Store<ItemState, ItemAction> {
    substore = Store(
      initialState: state,
      reducer: reducer,
//      reducer: reducer.debugActions(actionFormat: .labelsOnly),
//      reducer: reducer.signpost(),
      environment: environment
    )
    return substore!
  }
```

This solution solved all the problem with stack overflow we had with our recursive reducer and the performance and memory footprint has improved tremendously.

@stephencelis would it make sense to have a helper that would let us scope a child store that can run disconnected from its parent store?

I also don't understand why Apple implemented structs this way. It is quite crazy that you can follow the language specs to the letter and have random crashes and slow downs because the default stack size is set to an arbitrary value.

**Comment by stephencelis** [comment]
@DaanyalMeyer Sorry just seeing this. I'm not sure I understand your proposed fix without more code. Won't running a destination store in this disconnected manner prevent any communication back to the parent? If so, I think it probably makes more sense to be explicit about it as you are. But due to this behavior I don't think we'd consider this as a solution for stack issues, since a lot of the time the parent should be able to intercept child actions and observe child mutations.

How deeply are you navigating to encounter this issue? Scoping a store is definitely inefficient at the moment, frame-wise (something we're looking to address soon), but still only a handful of frames per scoping. I would _guess_ that this is still ample room to navigate dozens and maybe hundreds of screens deep. Do you know how many screens deep you hit before the stack overflows?
