### ISSUE TITLE
Inserting an element to an IdentifiedArray via a subscript doesn't work. Intentional?

### ISSUE THREAD

**Issue by pcolton** [pointfreeco/swift-composable-architecture#76]
**Describe the bug**

When inserting an element in an IdentifiedArray via a subscript, the internal id is not updated. At about line 100 of IdentifiedArray.swift:

```swift
public subscript(id id: ID) -> Element? {
    get {
      self.dictionary[id]
    }
    set {
      self.dictionary[id] = newValue
      if newValue == nil {
        self.ids.removeAll(where: { $0 == id })
      }
    }
  }
```

**To Reproduce**

```swift
self.myArray[id: newElement.id] = newElement
```

**Expected behavior**
I am not sure if this is intentional or not. I know I can also use .insert()

**Comment by stephencelis** [comment]
Definitely worth figuring out the right behavior here. It's currently undefined.

**Comment by pcolton** [comment]
Ok, I think the simplest fix, if you want to support the functionality of adding via subscript, would be to check the dictionary count after the assignment, and if it grows, add the new id to the list of id's.

**Comment by pcolton** [comment]
BTW, I mention this 'bug' because for parity sake, you can delete an element via:

```swift
self.myArray[id: newElement.id] = nil
```

**Comment by stephencelis** [comment]
Hey @pcolton! Just discussed this and think that the behavior of the subscript was perhaps not right. Instead of using it to remove/add elements, we think it's safest to reserve use for when you're _sure_ the element exists in the array.

Just pushed #80 to address, which adds a `remove(id:)` method and modifies the subscript behavior to assume that the element exists in the identified array.

**Comment by stephencelis** [comment]
Just merged! Thanks for bringing this up 😄
