### ISSUE TITLE
@BindableState property wrapper pattern matching

### ISSUE THREAD

**Issue by schneiderandre** [pointfreeco/swift-composable-architecture#809]
**Describe the bug**
When using the newly introduced `@BindableState` property wrapper with a struct and its own properties, like:

```swift
public struct AppState: Equatable {
    public var state: Bool
    @BindableState public var subState: SubState
}

public struct SubState: Equatable {
    public var name: Bool
    public var otherState: Bool
}
```

calling e.g:

```swift
TextField("Name", text: viewStore.$activity.name)
```

and switching over a specific property in the reducer does not work anymore:

```swift
public let reducer = Reducer<AppState, AppAction, AppEnvironment> { _, action, _ in
    switch action {
    case .binding(\.$subState.name):
        return .none
    case .binding:
        return .none
    }
}.binding()
```

The matching case falls through and is caught by the generic variant.

The refactoring is also covered by unit tests and the pattern correctly matches the first case, so

```swift
store.send(.binding(.set(\.$subState.state, true)))
```

works as expected.

**To Reproduce**

After debugging this during the refactoring and resolving the deprecations (using TCA version 0.27.1) I also checked out `isowords` and had a look at the changes made here:

[Use new binding helpers (#134) · pointfreeco/isowords@23d863a · GitHub](https://github.com/pointfreeco/isowords/commit/23d863a576d37b3e5c66a339f5dc01f0f434c707)

The issue is exactly the same:

```swift
@BindableState public var userSettings: UserSettings

...

ColorSchemePicker(colorScheme: self.viewStore.$userSettings.colorScheme)

...

case .binding(\.$userSettings.colorScheme):
```

`colorScheme` is not matched by the specific case but falls through to 

```swift
case .binding:
      return .none
```

And therefore does not switch to dark/light mode.
The same applies to all the other cases here.

And same with the unit tests:
```swift
 store.send(.set(\.$userSettings.colorScheme, .light))
```

They work just fine and the tests pass.

**Expected behavior**

Having a @BindableState struct with its own properties needs to work with case pattern matching as it did without the property wrapper before.

**Environment**
  - swift-composable-architecture version 0.27.1
  - Xcode 13 beta 4 (13A5201i) and Xcode 13 RC (13A233)
  - Swift 5.5
  - OS: iOS 15

**Comment by stephencelis** [comment]
Dang, good find! 😰 We really ought to have better smoke-tested this, and should have some view store tests in place for this.

It's tricky, but the bug is due to how dynamic member lookup works. The following:

```swift
self.viewStore.$userSettings.colorScheme
```

Is equivalent to:

```swift
self.viewStore[dynamicMember: \.$userSettings][dynamicMember: \.colorScheme]
```

The first lookup creates the binding action under the hood with the key path `\.$userSettings` and returns `Binding<UserSettings>`. The second lookup chains onto that binding, at which point we can no longer influence the binding action's key path. This means the reducer will never get a compound/nested key path, and so `case binding(\.$userSettings.colorScheme)` can never match.

The good news is there's a simple workaround. You can invoke the dynamic member lookup struct directly with the compound key path:

```swift
self.viewStore[dynamicMember: \.$userSettings.colorScheme]
```

The bad news is we're not sure dynamic member lookup is long for this world. We tried a few things, but it we couldn't figure out a good way to support dynamic member lookup for compound key paths.

I think our workaround will have to be to deprecate `viewStore.$field` syntax and instead introduce a slightly longer `viewStore.binding(\.$field)`. It's a bummer, but at least it's only modestly longer syntax.

If anyone figures out how to preserve dynamic member lookup, though, we'd love to see it!

**Comment by schneiderandre** [comment]
Thanks for the fast reply and provided workaround 💯 

I also had quick lock at https://github.com/pointfreeco/swift-composable-architecture/pull/810 and couldn't find another way of keeping the current dynamic member lookup.
