### ISSUE TITLE
Is there a Time-out for an Effect?

### ISSUE THREAD

**Issue by BrunoCerberus** [pointfreeco/swift-composable-architecture#917]
Is there a way to cancel an Effect, used for a request, after it starts through an time-out?

**Comment by mbrandonw** [comment]
Hi @BrunoCerberus, since `Effect` is just a standard Combine publisher you can use its [`timeout`](https://developer.apple.com/documentation/combine/publishers/merge/timeout(_:scheduler:options:customerror:)) operator to achieve what you want. If you use a [`TestScheduler`](https://github.com/pointfreeco/combine-schedulers) you'll even be able to write tests for the behavior.

**Comment by BrunoCerberus** [comment]
Nice, thanks a lot for the help, discovered that I can use a `.timeout(_:Scheduler)` right before a `catchToEffect` 🙃
